### ISSUE TITLE
Open link on a new tab

### ISSUE THREAD

**Issue by Hellements** [yokoffing/Betterfox#103]
Hello again, @yokoffing 
How to make Firefox to stay on the page when I click on a link, please? I would like to stay on page and links opening on background tabs.
Thank you, friend. :)

**Comment by yokoffing** [comment]
https://github.com/yokoffing/Betterfox/blob/56fb226db50b85d8654780f8cdd982b48bc3e8dd/Peskyfox.js#L313-L315

https://github.com/yokoffing/Betterfox/blob/6d07092eb37b010150ad9a30adfcb9070f300dce/Peskyfox.js#L328-L361

Read above, then try the `browser.tabs.loadInBackground` pref. That should be sufficient, but you're welcome to tinker with the other prefs if you want something more extreme.

**Comment by Hellements** [comment]
The command that worked was the browser.tabs.loadDivertedInBackground = true :)
Thank you.

**Comment by yokoffing** [comment]
> `browser.tabs.loadDivertedInBackground`

I don't think I've ever seen this used. Would you be able to share what website/programs showed a change in behavior for you?
