### ISSUE TITLE
[CMD] WidivineCmd plugin has crashed

### ISSUE THREAD

**Issue by gabinci** [yokoffing/Betterfox#105]
I have attempted the following troubleshooting suggestions:

- [x] [Cleared website data](https://www.hostinger.com/tutorials/wp-content/uploads/sites/2/2018/05/clear-browser-cache-firefox.png), restarted Firefox, and my issue persists.
- [x] No issues when using the website or extension in another web browser.
- [x] The issue persists when using Firefox in [Safe Mode](https://support.mozilla.org/en-US/kb/troubleshoot-firefox-issues-using-safe-mode#w_how-to-start-firefox-in-safe-mode).
- [x] Disabled DNS-level content blocking (AdGuard, NextDNS, PiHole), [cleared my DNS cache](https://www.pcmag.com/how-to/how-to-flush-your-dns-cache), and used my ISP's DNS resolver (if applicable).

## REPORT

I can't play encrypted videos. More specifically on [Udemy](https://www.udemy.com). Firefox sends a prompt:

> The WidevineCmd plugin has crashed.

**To Reproduce**

> _You may need to enable DRM_

1. Go to [udemy system-check](https://www.udemy.com/support/system-check/)
2. Scroll down to 'encrypted test video'
3. See error

**Expected behavior**
A video should play and WidivineCmd should not crash

**Desktop:**

- OS: Fedora-36 KDE plasma spin

**Comment by yokoffing** [comment]
Cannot reproduce. Do you have DRM disabled? Betterfox does not disable DRM by default.

Make sure these are enabled (set to `true`) in `about:config`:
https://github.com/yokoffing/Betterfox/blob/96ebe3ce57c1d0a6f59d3508142d6d36016e72ed/Securefox.js#L974-L995

**Comment by gabinci** [comment]
Yup, those are all set to true on my `about:config` + `user.js`. may it have something to do with my installation?

1. go to `about:profiles`
2. create a new profile (i use a custom location in my dotfiles, not firefox's default path)
3. create `user.js` file + copy  & paste from this repo.

If you want, I can provide a video of me performing the installation

**Comment by yokoffing** [comment]
I'm not seeing any issues with 'Encrypted test video` on Firefox stable or Nightly. However, I'm using Windows 11 and macOS; I don't have a Linux machine at the moment.

I just tried a fresh user.js + Firefox stable profile and had no issues.

My best guess is that it is a Firefox-on-Linux bug in general, or Fedora specific. I wouldn't think your custom profile location would affect anything, as long as it works and is loaded properly.

**Comment by gabinci** [comment]
the default Firefox config works fine, it's just when i change user.js it breaks

**Comment by yokoffing** [comment]
You could add parts of Securefox by sections to the user.js + restart to isolate the breakage.

I wouldn't think it's a pref in Fastfox or Peskyfox by default.

**Comment by gabinci** [comment]
i have no idea what is going on, I've made a new profile, copied the user.js file and commented every single line of code... it still breaks it.

**Comment by gabinci** [comment]
It seems as it may have something to do with creating new profiles on my machine. Both the `default` and `default-release` profiles work just fine. Custom profiles break `WidivineCmd` regardless of directory. I'll try some stuff and bring an update later on today.

**Comment by yokoffing** [comment]
I'm glad you can tinker with the default profiles at least.

Consider opening a report on [Bugzilla](https://bugzilla.mozilla.org/home).
