### ISSUE TITLE
remove repetition

### ISSUE THREAD

**Issue by botthebestplayerintheworld** [yokoffing/Betterfox#111]
https://github.com/yokoffing/Betterfox/blob/master/user.js#L253
https://github.com/yokoffing/Betterfox/blob/master/user-overrides.js#L75
https://github.com/yokoffing/Betterfox/blob/master/user-overrides.js#L78

**Comment by yokoffing** [comment]
Thank you. I had fixed the `user.js` for [next release](https://github.com/yokoffing/Betterfox/pull/108/commits), but missed the duplicate in my personal `overrides` file:  https://github.com/yokoffing/Betterfox/commit/681b9b1e7db468c5cc4c5578a75295f03f3e5864

I'll do code cleanup / consolidation once I get more feedback on all the changes in Fastfox. I have to be mindful of lower-end machines for the `user.js`.
