### ISSUE TITLE
Where do I create this file?

### ISSUE THREAD

**Issue by travisboss** [yokoffing/Betterfox#116]
I was looking at my `about:support` section and found `/Library/Application Support/Firefox/Profiles/yrhwfusd.default-release` folder, do I simply create the `user.js` file here and copy/pasta?  I do see my `pref.js` file in this same location.

Thanks.

**Comment by yokoffing** [comment]
Yes, the `Root Directory` location. The `user.js` overrides the `pref.js` every restart of Firefox.
