### ISSUE TITLE
How do I update the user.js?

### ISSUE THREAD

**Issue by Mercyletter** [yokoffing/Betterfox#129]
Hi, a newbie question sorry. I would like to know how to update the user.js version after version keeping the modifications I made. Thank you very much for your work. Best regards.

**Comment by yokoffing** [comment]
https://github.com/yokoffing/Betterfox/blob/229d6697baae385de9a979900d0bc15693e7df5d/user.js#L4-L8

Put your modifications ("overrides") at the bottom of the file, and move them over when you update your user.js.

https://github.com/yokoffing/Betterfox/blob/229d6697baae385de9a979900d0bc15693e7df5d/user.js#L271-L275

**Comment by Mercyletter** [comment]
Thank you very much, best regards!
