### ISSUE TITLE
The website loads but then everything disappears

### ISSUE THREAD

**Issue by SampeiNihira** [yokoffing/Betterfox#141]
## BEFORE YOU BEGIN
I have attempted the following troubleshooting suggestions:
- [x] Disabled DNS-level content blocking (Control D, RethinkDNS, AdGuard Home, NextDNS, PiHole, etc), [cleared my DNS cache](https://www.pcmag.com/how-to/how-to-flush-your-dns-cache), and used my ISP's DNS resolver (if applicable).
- [x] [Cleared website data](https://www.hostinger.com/tutorials/wp-content/uploads/sites/2/2018/05/clear-browser-cache-firefox.png), restarted Firefox, and my issue persists.
- [x] The issue persists when using the current, recommended [user.js](https://github.com/yokoffing/Betterfox/blob/master/user.js) in a [new profile](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles).

## REPORT
The website https://www.walmart.com/ initially loads the content then suddenly everything disappears and the web page remains empty.
The problem is not solved even by disabling uBlock Origin.
The problem is not solved even by disabling anti-trackers protection for the website.

The problem is solved with the default profile.

**To Reproduce**

1. Open website

2. Wait for the web page to finish loading

**Expected behavior**
That the web page shows its content

**Screenshots**
Current behavior:

![1](https://user-images.githubusercontent.com/44166263/212694340-6f42df19-623c-444c-b265-65843abf7963.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2
 - Browser Firefox
 - Version 108.0.2

**Additional context**

The open website with Edge:
![2](https://user-images.githubusercontent.com/44166263/212695123-efa65abe-38db-402f-a619-a99c58e6c6f7.jpg)

**Comment by yokoffing** [comment]
The site works fine for me using:
1.  a new Firefox profile 108.0.2
2. same profile + with uBO default setup
3. Firefox Nightly

Your screenshot tells me that you have uBO in [hard mode](https://github.com/gorhill/uBlock/wiki/Blocking-mode:-hard-mode), and that will break the site in Firefox. So did you disable this and then clear the cache?

![walmart blocking 3rd party2](https://user-images.githubusercontent.com/11689349/212706196-cb9275eb-dac7-464b-9892-4a8af3ce7652.png)

**Comment by SampeiNihira** [comment]
Even in safe mode there is no change.
So no disturbing extensions.
I use UBO + TLD's but I wrote you that the problem persists if I disable UBO.

It will probably be a setting I changed before using your js.
If you using js only you have the website working.
Sorry for wasting your time.

**Comment by yokoffing** [comment]
> I wrote you that the problem persists if I disable UBO

Yes, but your screenshot showed it still enabled. So I deferred to the screenshot and raised the question to double-check :smile:
