### ISSUE TITLE
PDF.js broken with Fastfox

### ISSUE THREAD

**Issue by pklion** [yokoffing/Betterfox#153]
## BEFORE YOU BEGIN
I have attempted the following troubleshooting suggestions:
- [ ] The issue persists when using Firefox in [Troubleshoot Mode](https://support.mozilla.org/en-US/kb/diagnose-firefox-issues-using-troubleshoot-mode).
- [x] Disabled DNS-level content blocking (AdGuard Home, NextDNS, Control D, RethinkDNS, PiHole, etc), [cleared my DNS cache](https://www.pcmag.com/how-to/how-to-flush-your-dns-cache), and used my ISP's DNS resolver (if applicable).
- [x] [Cleared website data](https://support.mozilla.org/en-US/kb/clear-cookies-and-site-data-firefox), restarted Firefox, and my issue persists.
- [x] I have created a [new profile](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles). The issue persists when using the current [user.js](https://github.com/yokoffing/Betterfox/blob/master/user.js) file on GitHub. (Must be in a new profile and a new user.js!)

## REPORT
**Describe the bug**
I copied [Fastfox section of user.js](https://github.com/yokoffing/Betterfox/blob/master/user.js#L17) into my user.js, and the PDF viewer seems broken.

**To Reproduce**

```
1. Copy Fastfox section into user.js
2. Open Firefox
3. Open https://www.africau.edu/images/default/sample.pdf
```

**Expected behavior**
Please don't make the PDF viewer broken.

**Screenshots**
![image](https://user-images.githubusercontent.com/78145811/219027906-0230b53a-3f88-40eb-9a9a-9d4646f3f880.png)

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [Firefox Nightly (Latest)]

**Additional context**

**Comment by yokoffing** [comment]
I did not reproduce the issue using `https://www.africau.edu/images/default/sample.pdf` or any other PDF. None of the FastFox prefs have anything to do with PDF rendering. Therefore, my suspicion is that this is correlation and not causation.

Please edit the post and indicate that you've completed the "BEFORE YOU BEGIN" steps.

**Comment by pklion** [comment]
@yokoffing Thank you for your reply.
I tried these steps with **a new profile(I haven't added any addons),** and only Troubleshoot Mode worked.

**Comment by pklion** [comment]
I don't know but maybe it only happens with Firefox Nightly.

**Comment by yokoffing** [comment]
If it doesn't happen in troubleshoot mode, then it may have something to do with [hardware acceleration](https://support.mozilla.org/en-US/kb/troubleshoot-extensions-themes-to-fix-problems).

If you are only using the FastFox portion of the user.js, and no other changes, I would
1) Remove the user.js from the profile
2) Go to `about:config`
3) Go through [this list](https://github.com/yokoffing/Betterfox/blob/07c7bbe6bab92f8e9283cb33b176bce5439a686b/Fastfox.js#L158-L181) and manually turn the settings back to their default (the arrow will show up for each pref changed in `about:config`).
4) One-by-one, reset the pref, and restart Firefox, and see if your issue improves.

**Comment by pklion** [comment]
For my PC (Firefox Nightly on Surface Pro 8), commenting [gfx.canvas.accelerated](https://github.com/yokoffing/Betterfox/blob/07c7bbe6bab92f8e9283cb33b176bce5439a686b/Fastfox.js#L181) out fixed the problem.
Could you please comment out that option by default or write some notes in Fastfox.js about its effect if you don't mind?
Anyway, thank you so much for your support. :)

**Comment by yokoffing** [comment]
Thank you for reporting this issue. I made a note on the next release of `Fastfox.js`. Hopefully, Mozilla will iron out all the bugs with it soon so you can enable it.

If you do find that in a few months that it works as intended, let me know, and I'll remove the warning.

**Comment by pklion** [comment]
Thank you!
