### ISSUE TITLE
Update new brave list for privacy.query_stripping.strip_list

### ISSUE THREAD

**Issue by gnadgnaoh** [yokoffing/Betterfox#158]
https://github.com/brave/adblock-lists/blob/master/brave-lists/clean-urls.json

**Comment by yokoffing** [comment]
Firefox only supports global clearing.

For an advanced solution, use uBlock Origin and add [these lists](https://github.com/yokoffing/filterlists#url-tracking-parameters). They can limit which URL tracking parameters are cleared from specific domains.

**Comment by gnadgnaoh** [comment]
Thank you
