### ISSUE TITLE
Overrides for setting the default browser

### ISSUE THREAD

**Issue by Uranite** [yokoffing/Betterfox#166]
Hi, I noticed that there is `user_pref("browser.shell.checkDefaultBrowser", false);` on peskyfox, I tried to set it to true in the overrides, while the popup does show up, after pressing "Set as default browser" it still doesn't set firefox as the default browser (e.g chrome is still set as the default browser).
I think that there might be other prefs that's preventing it to work. I'm thinking that maybe you know what prefs that is?
For clarity, I'm talking about this thing:
![image](https://user-images.githubusercontent.com/62639703/232172144-01437f79-43f2-4bd0-b3f0-5ab36e999926.png)

**Comment by yokoffing** [comment]
![Screenshot 2023-04-14 202026](https://user-images.githubusercontent.com/11689349/232174069-14f1015e-f498-4221-8881-e36c12f4704c.png)

I have found that when using the whole `user.js,` using Firefox's `Make Default` button doesn't work.

**Comment by Uranite** [comment]
I just found out that its the prefs `user_pref("default-browser-agent.enabled", false);` thats causing setting default browser to not work
so the overrides would be:
```
user_pref("default-browser-agent.enabled", true);
user_pref("browser.shell.checkDefaultBrowser", true);
```

**Comment by yokoffing** [comment]
Yes, when I glanced at the list, `user_pref("default-browser-agent.enabled", true);` is what I most suspected, but I had not dedicated time to test it.

**Comment by yokoffing** [comment]
Thank you for reporting. I've made notes in Pesky & Secure, and updated the Overrides issue.
