### ISSUE TITLE
Peskyfox: Set browser.vpn_promo.enabled to false

### ISSUE THREAD

**Issue by kevindwitama** [yokoffing/Betterfox#169]
See reddit post: https://www.reddit.com/r/firefox/comments/13ro31o/mozilla_sends_popup_ad_overlay_in_firefox/

Highly intrusive ad from Mozilla that prevents interaction.

**Comment by yokoffing** [comment]
I haven't encountered this (yet?).

**Comment by kevindwitama** [comment]
To be fair I also personally haven't encountered it, but the setting was there in about:config in Nightly, and it doesn't hurt keeping it disabled.

**Comment by yokoffing** [comment]
> it doesn't hurt keeping it disabled

... for you. It's maintenance burden for me if it's not needed. So, I've added it to Pesky as optional.

Mozilla [backtracked](https://support.mozilla.org/en-US/questions/1414266#answer-1582507) on displaying the VPN ad, even though the pref in Firefox is still `true`.
