### ISSUE TITLE
disabling the menu bar on alt

### ISSUE THREAD

**Issue by wis3f1sh** [yokoffing/Betterfox#179]
I suggest disabling the menu bar in Peskyfox.js and user.js. 
When you press alt, an annoying menu bar appears, sometimes preventing you from changing windows. 
Here is the code to disable it: 
`user_pref("ui.key.menuAccessKeyFocuses", false);`

**Comment by HyperCriSiS** [comment]
This is the common way to open this menu.
If this prevents you sometimes from switching windows, this must be an issue in your system.
The menu only appears as soon as the alt key is released.

**Comment by yokoffing** [comment]
Thank you for reporting. 

The pref `ui.key.menuAccessKey` has been [optional in Peskyfox ](https://github.com/yokoffing/Betterfox/blob/f7f0d799ee6a02f425315b49aff5f7245b7dad00/Peskyfox.js#L439-L440) for awhile now, but the pref you suggested makes more sense. [Added](https://github.com/yokoffing/Betterfox/commit/04c3184359c83d7b58411c3b68f40f3e9d95c373) to Peskyfox.

However, I consider this a niche issue; and as HyperCrisis said, some people use this key as a part of their workflows.

Please add the pref you suggested to your [overrides](https://github.com/yokoffing/Betterfox/issues/87).
