### ISSUE TITLE
Floorp Project Reference

### ISSUE THREAD

**Issue by surapunoyousei** [yokoffing/Betterfox#189]
Hi [yokoffing](https://github.com/yokoffing).

I posted a license notice on Floorp as per your Reddit comment. Please check if there is a problem with how it is written.

https://github.com/Floorp-Projects/Floorp#-betterfox

I'm new to Reddit and didn't know how to contact you.

**Comment by yokoffing** [comment]
Hi! Yes, this is okay with me.

Thank you for asking 🙂
