### ISSUE TITLE
network.http.pipelining

### ISSUE THREAD

**Issue by wis3f1sh** [yokoffing/Betterfox#193]
I suggest adding two parameters to Fastfox and user.js that will speed up Firefox.
`network.http.pipelining` -> `true`
`network.http.proxy.pipelining` -> `true`
`network.http.pipelining.maxrequests` -> `30` [Set "network.http.pipelining.maxrequests" to, for example, 30, which means it will make 30 requests at a time.]

**Comment by yokoffing** [comment]
Network support for `pipelining` was completely [removed in Firefox](https://support.mozilla.org/en-US/questions/1166780) 54, which was released in 2017, and [removed from Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=364557) in 2014.
