### ISSUE TITLE
Numbers on Desmos graph axes appear glitched (gfx.canvas.accelerated)

### ISSUE THREAD

**Issue by cmrss2** [yokoffing/Betterfox#198]
## BEFORE YOU BEGIN
I have attempted the following troubleshooting suggestions:
- [-] The issue persists when using Firefox in [Troubleshoot Mode](https://support.mozilla.org/en-US/kb/diagnose-firefox-issues-using-troubleshoot-mode).
- [☑️] Disabled DNS-level content blocking (AdGuard Home, NextDNS, Control D, RethinkDNS, PiHole, etc), [cleared my DNS cache](https://www.pcmag.com/how-to/how-to-flush-your-dns-cache), and used my ISP's DNS resolver (if applicable).
- [☑️] [Cleared website data](https://support.mozilla.org/en-US/kb/clear-cookies-and-site-data-firefox), restarted Firefox, and my issue persists.
- [☑️] I have created a [new profile](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles). The issue persists when using the current [user.js](https://github.com/yokoffing/Betterfox/blob/master/user.js) file on GitHub. (Must be in a new profile and a new user.js!)

## REPORT
**Describe the bug**
*A clear and concise description of what the bug is.*
When using the Desmos graphing calculator, the numbers on the axes appear glitched.

**To Reproduce**
*Steps to reproduce the behavior:*

1. Go to 'https://www.desmos.com/calculator'
2. See error

**Expected behavior**
*A clear and concise description of what you expected to happen.*
The numbers on the axes should be clearly readable.

**Screenshots**
*If applicable, add screenshots to help explain your problem.*
![image](https://github.com/yokoffing/Betterfox/assets/77649553/bb0cb7c3-23b1-40e6-b4de-041b7d00aff8)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version 115.0.2 (Betterfox 115)

**Additional context**
*Add any other context about the problem here.*
This only occurs in non-troubleshooting mode. Troubleshooting mode disables hardware acceleration, which fixes it. A default profile of Firefox with hardware acceleration enabled works fine, so it must be something in the user.js.

**Comment by axydavid** [comment]
can confirm from my firefox dev windows 11:
![image](https://github.com/yokoffing/Betterfox/assets/11884779/d2806e4a-8ef5-4cf4-a7ad-cebe2a9a7589)

the issue persists across various websites, suspect maybe when used in correlation with canva.

**Comment by axydavid** [comment]
UPDATE:
![image](https://github.com/yokoffing/Betterfox/assets/11884779/c9d02562-83dd-4148-b21a-d635c6dfb99e)

My suspicions were correct!

fix: 
change 
`user_pref("gfx.canvas.accelerated", true);`
to
`user_pref("gfx.canvas.accelerated", false);`

restart ff

**Comment by yokoffing** [comment]
@axydavid I have access to my Windows machine now.

> This issue is widespread across various websites

Can you list the websites? It may help troubleshoot, or to help hunt down / create a Bugzilla ticket.

> `https://www.desmos.com/calculator`

On Windows 11 with a new FF Stable profile and `gfx.canvas.accelerated` = `true` (not using the `user.js`), this does not occur.

I also cannot reproduce on Firefox Nightly **with** the `user.js`.

**Comment by axydavid** [comment]
i use integrated intel graphics, as i'm using a laptop. The websites affected are all websites that use canvas.

**Comment by yokoffing** [comment]
@axydavid As of version 116, we've [commented out](https://github.com/yokoffing/Betterfox/blob/2b8b671fe1b60339527a084eeebd446a6780504d/user.js#L31) `gfx.canvas.accelerated` by default.
