### ISSUE TITLE
Google Maps

### ISSUE THREAD

**Issue by wis3f1sh** [yokoffing/Betterfox#203]
## BEFORE YOU BEGIN
I have attempted the following troubleshooting suggestions:
- [ ] The issue persists when using Firefox in [Troubleshoot Mode](https://support.mozilla.org/en-US/kb/diagnose-firefox-issues-using-troubleshoot-mode).
- [ ] Disabled DNS-level content blocking (AdGuard Home, NextDNS, Control D, RethinkDNS, PiHole, etc), [cleared my DNS cache](https://www.pcmag.com/how-to/how-to-flush-your-dns-cache), and used my ISP's DNS resolver (if applicable).
- [ ] [Cleared website data](https://support.mozilla.org/en-US/kb/clear-cookies-and-site-data-firefox), restarted Firefox, and my issue persists.
- [ ] I have created a [new profile](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles). The issue persists when using the current [user.js](https://github.com/yokoffing/Betterfox/blob/master/user.js) file on GitHub. (Must be in a new profile and a new user.js!)

## REPORT
**Describe the bug**
on google maps site "globe mode" is not available and zooming is intermittent

**To Reproduce**
I go to google maps and observe the inability to turn on "globe mode" and intermittent zooming

```
1. Go to google maps
2. Click on layers
3. Scaling the map
4. See error
```

**Expected behavior**
globe mode on google maps and smooth zooming

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

https://github.com/yokoffing/Betterfox/assets/97912016/18031d5b-e705-4ab8-b8d5-991287f3071d

**Desktop (please complete the following information):**
 - Windows 10 22H2 x64
 - Firefox
 - 116.0

**Additional context**
*Add any other context about the problem here.*

**Comment by yokoffing** [comment]
I **cannot** reproduce on Firefox Stable using a new profile or when using the current `user.js`.

I **can** reproduce on my build with Firefox Nightly.

There are many bug reports across various browsers reporting this issue in the past 5 years, but none of them I've found post what the solution was. Many seem to point to the browser not being able to use WebGL. You can test if Firefox can use WebGL with this site: https://get.webgl.org/

On Stable (with or without `user.js`):

![stable](https://github.com/yokoffing/Betterfox/assets/11689349/6dc5100e-1a62-4397-acf3-ec342c52fbf8)

On Nightly w/ `user.js`:

![nightly](https://github.com/yokoffing/Betterfox/assets/11689349/b4434ff5-1341-431b-b753-73869dbd5548)

**Comment by wis3f1sh** [comment]
Indeed, the essence of the problem is in the *enabled* parameter `about:config` `webgl.disabled`. After disabling it, the problem is solved. The only remaining question is whether this parameter is in user.js or related to something else?

**Comment by yokoffing** [comment]
`webgl.disabled` is not in the [user.js](https://raw.githubusercontent.com/yokoffing/Betterfox/main/user.js). It's [stated in the README](https://github.com/yokoffing/Betterfox#aboutprivacy) that we don't break user experiences like this.

Most issues are due to users toggling prefs outside the `user.js`, which is why the `BEFORE YOU BEGIN` section exists for bug reports...

In the future, **bug reports not following through with self-troubleshooting will be auto-closed.**
