### ISSUE TITLE
separate search bar from URL bar

### ISSUE THREAD

**Issue by wis3f1sh** [yokoffing/Betterfox#204]
Due to the fact that the current `user.js` has disabled search suggestions for privacy, I suggest disabling search from the address bar altogether, as already implemented in `ungoogled chromium` with the `nosearch` search provider.
To do this, you need to add user_pref such as:
```
user_pref("browser.urlbar.suggest.searches", false);
user_pref("keyword.enabled", false);
user_pref("browser.fixup.alternate.enabled", false);
```

**Comment by yokoffing** [comment]
I understand the logic, but this would break too many people's workflows (user expectation).

Yes, [live search suggestions are disabled](https://github.com/yokoffing/Betterfox/blob/7c5aeccecb97e6c47f180adb22b9fa2033884bea/Securefox.js#L606-L609) for privacy, but that doesn't mean most users want to enable a separate search bar to search for something (hello early 00's), or, for users who won't understand how to do that, think that they have to navigate to `google.com` etc. every time they want to search. Enthusiasts who want that usually know how to achieve it.

Users who want a separate search bar from the address bar + autocomplete search results in search bar can add to their overrides:

```
// PREF: perform search engine queries in a separate search bar
user_pref("browser.search.widget.inNavBar", true); // display search bar beside the URL bar
user_pref("browser.search.suggest.enabled", true); // DEFAULT; restore autocomplete search suggestions
user_pref("keyword.enabled", false); // disable URL bar from resolving search queries 
```

Btw, `browser.fixup.alternate.enabled` `false` is already default.

Even though many people tout Ungoogled Chromium as a great browser, it removes too much, IMO.
