### ISSUE TITLE
Typing causes search box to appear

### ISSUE THREAD

**Issue by proJM-Coding** [yokoffing/Betterfox#212]
When you type outside of a text box it makes the search box to appear, is there a fix/change to turn this off? I think if it isn't added yet it would be great for Peskyfox.

**Comment by yokoffing** [comment]
This is not enabled by default, so it won't be added to the user.js.

![Screenshot 2023-08-18 092955](https://github.com/yokoffing/Betterfox/assets/11689349/17d4e60e-5973-4fe4-baaa-60f09ec28d52)

In `about:config`, it's `accessibility.typeaheadfind`.

***

I used this for a little while, but it's not as powerful as `Ctrl` + `F`.

I thought we had it documented, but I guess we haven't. I will add to Peskyfox.

**Comment by proJM-Coding** [comment]
Sorry, I must have missed this setting. Thanks for the help and addition.
