### ISSUE TITLE
Enable auto scrolling by default

### ISSUE THREAD

**Issue by nonetrix** [yokoffing/Betterfox#219]
On Linux for some reason auto scrolling is disabled by default, this allows you to scroll faster or scroll left or right by holding down the middle mouse button. One of the first settings I change because it's annoying without it personally. For whatever reason it's already enabled on Windows and maybe MacOS, but on Linux it isn't, personally haven't had any bugs with it or anything so I have no idea why it's like this

**Comment by nonetrix** [comment]
Chrome also just doesn't have auto scrolling on Linux at all, so maybe it's something I'm just not aware of I'm not entirely sure

**Comment by soredake** [comment]
> personally haven't had any bugs with it or anything so I have no idea why it's like this

Most likely to not conflict with middle click paste behavior https://wiki.archlinux.org/title/Clipboard#Middle-click_behavior

**Comment by yokoffing** [comment]
> Most likely to not to conflict with middle click paste behavior `https://wiki.archlinux.org/title/Clipboard#Middle-click_behavior`

I have it disabled in my personal overrides for this very reason:

`user_pref("general.autoScroll", false); // disable unintentional behavior for middle click`

**Comment by nonetrix** [comment]
Well I guess I'll close the issue in this case
