### ISSUE TITLE
`network.trr.mode 0` is now ~enabled

### ISSUE THREAD

**Issue by alana-glitch** [yokoffing/Betterfox#229]
This line: https://github.com/yokoffing/Betterfox/blob/0334bea9721fa734506160f0770515817c094972/Securefox.js#L647

Says the setting at 0 means disabled. In FF117 (unsure when this changed), 0 means "default" which is "sometimes enabled":

<img width="706" alt="Screenshot 2023-09-19 at 2 19 36 PM" src="https://github.com/yokoffing/Betterfox/assets/62029416/096c4b5f-a177-44ee-9282-e14ebe426b2c">
<img width="367" alt="Screenshot 2023-09-19 at 2 19 26 PM" src="https://github.com/yokoffing/Betterfox/assets/62029416/f35a8a50-9610-4ec1-b74b-30f7be3b9c84">

**Comment by iam-py-test** [comment]
Only mildly related, but maybe there should be a note recommending people use something other than CloudFlare for their DOH.

**Comment by yokoffing** [comment]
> @alana-glitch Says the setting at 0 means disabled. In FF117 (unsure when this changed), 0 means "default" which is "sometimes enabled

You are correct. This will be updated in v.118 documentation. https://github.com/yokoffing/Betterfox/commit/2e03ce1ad06c92b2c2f19f0db11b75e03d99d132

> @iam-py-test maybe there should be a note recommending people use something other than CloudFlare for their DOH.

Added a note. https://github.com/yokoffing/Betterfox/commit/873cc4476f40614189b3a8cbbaa5ff70baa1c88a
