### ISSUE TITLE
browser.ctrlTab.recentlyUsedOrder -> browser.ctrlTab.sortByRecentlyUsed

### ISSUE THREAD

**Issue by alana-glitch** [yokoffing/Betterfox#230]
This line: 

https://github.com/yokoffing/Betterfox/blob/0334bea9721fa734506160f0770515817c094972/Peskyfox.js#L465C5-L465C10

References a preference that does not exist by default, or seem to do anything. (MacOS, FF117) For me, the default ctrl-tab behavior is in-order. The setting `browser.ctrlTab.sortByRecentlyUsed` does exist though, and setting it to true makes ctrl-tab sort by recently used.

Suggest update to:

```javascript
// PREF: CTRL+TAB cycles tabs in recently-used order instead
// of tab order.
//user_pref("browser.ctrlTab.sortByRecentlyUsed", true);
```

**Comment by yokoffing** [comment]
Thank you! This will be fixed in the next update.

I'm also leaving myself a note to fix this in the ESR branch when I'm back from out-of-town.
