### ISSUE TITLE
Unable to use search in address bar

### ISSUE THREAD

**Issue by iansquenet** [yokoffing/Betterfox#231]
## BEFORE YOU BEGIN
I have attempted the following troubleshooting suggestions:
- [x] The issue persists when using Firefox in [Troubleshoot Mode](https://support.mozilla.org/en-US/kb/diagnose-firefox-issues-using-troubleshoot-mode).
- [x] Disabled DNS-level content blocking (AdGuard Home, NextDNS, Control D, RethinkDNS, PiHole, etc), [cleared my DNS cache](https://www.pcmag.com/how-to/how-to-flush-your-dns-cache), and used my ISP's DNS resolver (if applicable).
- [x] [Cleared website data](https://support.mozilla.org/en-US/kb/clear-cookies-and-site-data-firefox), restarted Firefox, and my issue persists.
- [x] I have created a [new profile](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles). The issue persists when using the current [user.js](https://github.com/yokoffing/Betterfox/blob/master/user.js) file on GitHub. (Must be in a new profile and a new user.js!)

## REPORT
**Describe the bug**
*I'm trying to have it so I could use Startpage's search engine on the address bar and not on the separate search bar. Instead I get a "visit" and only able to search for links/URLs.*

**To Reproduce**
*I've gone through all the categories and this is what I came up with so far in my overrides (note that I have syncs enabled)*

```
// PREF: restore Firefox View UI
user_pref("browser.tabs.firefox-view", enable);

// PREF: restore Firefox accounts
user_pref("identity.fxaccounts.enabled", true);

// PREF: Push API seems to be needed for Sync (not needed after v. 108)
user_pref("dom.push.enabled", true);

/** URL BAR ***/
user_pref("browser.urlbar.suggest.engines", false);
user_pref("browser.urlbar.suggest.topsites", false);
user_pref("browser.urlbar.suggest.calculator", true);
user_pref("browser.urlbar.unitConversion.enabled", true);

/** SEARCH / URL BAR ***/
user_pref("browser.search.separatePrivateDefault.ui.enabled", true);
user_pref("browser.urlbar.update2.engineAliasRefresh", true);
user_pref("browser.search.suggest.enabled", false);
user_pref("browser.urlbar.suggest.quicksuggest.sponsored", false);
user_pref("browser.urlbar.suggest.quicksuggest.nonsponsored", false);
user_pref("browser.formfill.enable", false);
user_pref("security.insecure_connection_text.enabled", true);
user_pref("security.insecure_connection_text.pbmode.enabled", true);
user_pref("network.IDN_show_punycode", true);
```

**Expected behavior**
*I expected it to allow me to do searching from the address bar without having to do the @ every time I wanna search.*

**Desktop (please complete the following information):**
 - OS: [Windows 10}
 - Browser [Firefox]
 - Version [118.0b9]

**Comment by yokoffing** [comment]
The search itself is not working, or search suggestions do not show as you’re typing in the URL bar?

**Comment by iansquenet** [comment]
> The search itself is not working (doesn’t resolve after you press enter), or search suggestions do not show as you’re typing in the URL bar?
> 
> One is the intended behavior with Betterfox and the other is not, so the distinction is important.

Yes, the search itself is not working, only able to use it for links. Though I'd like to use the search like before.

**Comment by iansquenet** [comment]
I figured it out! Went to about:config and changed the "keyword.enabled" to true :)
