### ISSUE TITLE
Google domains don't work. Is this intended?

### ISSUE THREAD

**Issue by cybernaut4** [yokoffing/Betterfox#232]
## BEFORE YOU BEGIN
I have attempted the following troubleshooting suggestions:
- [x] The issue persists when using Firefox in [Troubleshoot Mode](https://support.mozilla.org/en-US/kb/diagnose-firefox-issues-using-troubleshoot-mode).
- [x] Disabled DNS-level content blocking (AdGuard Home, NextDNS, Control D, RethinkDNS, PiHole, etc), [cleared my DNS cache](https://www.pcmag.com/how-to/how-to-flush-your-dns-cache), and used my ISP's DNS resolver (if applicable).
- [x] [Cleared website data](https://support.mozilla.org/en-US/kb/clear-cookies-and-site-data-firefox), restarted Firefox, and my issue persists.
- [x] I have created a [new profile](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles). The issue persists when using the current [user.js](https://github.com/yokoffing/Betterfox/blob/master/user.js) file on GitHub. (Must be in a new profile and a new user.js!)

## REPORT
**Describe the bug**
Nothing from Google works.

**To Reproduce**
Follow the steps from the README of this repo

**Expected behavior**
Any website would work without Firefox sending data on its own gratis, nor asking nor suggesting password managing, auto-data completion, all the extra gibberish and the hidden stuff I may not know yet because I haven't been a Firefox guy for the last 5 years.

**Screenshots**

![image](https://github.com/yokoffing/Betterfox/assets/68290346/b611dcc2-9adc-431a-98d2-3fcdb4add85e)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 117.0.1 (64-bit)

## ADDITIONAL CONTEXT
I made a search from visual studio code with the word "google" and it didn't find any blacklist file within the profile directory. Nor in the settings page except for the default search engine, which isn't the point.

Default settings work, so clearly it's something the user.js did but I can't pinpoint where and/or how.

**Comment by cybernaut4** [comment]
I added Additional Context section.

**Comment by yokoffing** [comment]
https://github.com/yokoffing/Betterfox/wiki/Common-Overrides#public-key-pinning-pkp

**Comment by cybernaut4** [comment]
There was a pending Windows Update, so I let it update before leaving for a couple of minutes. 
Now Firefox can load Google websites with the user.js.

> https://github.com/yokoffing/Betterfox/wiki/Common-Overrides#public-key-pinning-pkp

In the end I didn't need to change the enforcement level that you linked, but it's good to know there is an alternative solution.
