### ISSUE TITLE
Tweaking nglayout.initialpaint.delay

### ISSUE THREAD

**Issue by gunir** [yokoffing/Betterfox#239]
Wiki: http://kb.mozillazine.org/Nglayout.initialpaint.delay

> Mozilla applications render web pages incrementally - they display what's been received of a page before the entire page has been downloaded. Since the start of a web page normally doesn't have much useful information to display, Mozilla applications will wait a short interval before first rendering a page. This preference controls that interval. 
> Lower values will make a page initially display more quickly, but will make the page take longer to finish rendering. Higher values will have the opposite effect. 

Currently Betterfox is using 0 for this key, but Firefox rendering engine isn't tweaked for displaying page instantly like Chrome, in some cases (slow computer or Dark Reader), lowering this value hurts performance by a lot: https://old.reddit.com/r/firefox/comments/o0xl1q/reducing_cpu_usage_of_dark_reader_extension/

We should list more options and explain to users how to pick their best value instead, for example:

- For fast computer, leave it be at 5 or lower to 0
- For slow computer, 250
- For Dark Reader users, 1000-2000

Thanks for reading.

**Comment by yokoffing** [comment]
2000ms is awfully slow on a modern machine.

**Comment by WilderWes** [comment]
Is it still recommended to enable 1000ms paint delay for dark reader extension on firefox 146?

**Comment by yokoffing** [comment]
@WilderWes Yes, as far as I know.
