### ISSUE TITLE
Support FF Beta and Developer Edition?

### ISSUE THREAD

**Issue by entrider** [yokoffing/Betterfox#241]
I suggest to add a persistent `beta` branch that Firefox Beta users can use. I'm aware about 119 branch, but it's unclear if its safe to use or not.

Why? Because beta and nightly versions are usually better performance-wise.

**Comment by yokoffing** [comment]
Thanks for reaching out!

You have a point, but for a small project, that level of customization for minor preferences is excessive.

I already include useful features from Nightly and Beta in the docs, which is already time-consuming.

119 is not final. The 119 branch is the upcoming Betterfox changes. It aligns with upcoming the Firefox stable release.

**Comment by entrider** [comment]
For Firefox Beta users would it be better to use main or 119 branch?

**Comment by yokoffing** [comment]
The 119 branch is not finalized yet. It will be merged into the main branch once finalized. Use that information as you see fit.

**Comment by entrider** [comment]
Arkenfox author says that there arent any major changes in recent versions:
https://github.com/arkenfox/user.js/blob/b3ea0b89d49796a90f24b8ac7789bc671170d1d9/user.js#L31
https://github.com/arkenfox/user.js/issues/1692
Is it because they only count for privacy/security related settings? And Betterfox is more complex.
