### ISSUE TITLE
Top sites (pinned site shortcuts) are removed for a clean new tab page.

### ISSUE THREAD

**Issue by iamthelara** [yokoffing/Betterfox#242]
Is this possible to clear topsites (which is recently searched)? Some sites are getting injected into rows. I have activated this .js but I just visited codeberg and it got appeared into rows.

**Comment by iamthelara** [comment]
![Uploading SNAG-0000.png…]()

**Comment by iamthelara** [comment]
![SNAG-0000](https://github.com/yokoffing/Betterfox/assets/50659607/b00475f0-245e-47c0-9bc4-7d8e830d2707)

**Comment by yokoffing** [comment]
I don't use these. I believe you can remove them by right-clicking. If not, then no.

#### Alternatives
* [Bookmark keywords](https://felixcrux.com/blog/favourite-firefox-feature-keyword-search-bookmarks) provide a better experience ([YouTube example](https://youtu.be/bGTBH9yr8uw?si=FvQGmZqFz9n2JZT0&t=1080)).
* Learn how to [narrow down suggestions](https://support.mozilla.org/en-US/kb/address-bar-autocomplete-firefox#w_changing-results-on-the-fly) in the URL bar by a specific type of result (`*` for bookmarks, `^` for browser history, etc.).

**Comment by iam-py-test** [comment]
> you can remove them by right-clicking.

Doesn't seem to work for me.
I can hover over them, click the three dots, and then click "Dismiss"
![image](https://github.com/yokoffing/Betterfox/assets/84232764/c86876bd-ed69-47d8-b9ba-606310cecb0b)
Thanks

**Comment by yokoffing** [comment]
@iam-py-test OP didn't show three dots in their post, but I do recall that being a thing. I haven't been able to test today.

Thanks. Cheers
