### ISSUE TITLE
Disabling reader mode parsing (and Firefox Screenshots?)

### ISSUE THREAD

**Issue by 70T** [yokoffing/Betterfox#243]
Two options that I have a habit of tweaking on my installations of Firefox have been the following:

`reader.parse-on-load.enabled` = false
&
`extensions.screenshots.disabled` = true

I believe that disabling the reader more page parsing would be beneficial for performance purposes. Additionally, assuming that Screenshots is not deprecated (I couldn't find any up-to-date documentation on the subject), also disabling that feature should free up a miniscule amount of resources in exchange for disabling a feature that likely sees very little usage. (You can also still take screenshots from the developer console with :screenshot).

**Comment by 70T** [comment]
Surely the reader parsing would add some delay to page loading? 

I thought so with the screenshots feature, though. 

How do you disable reader entirely?

**Comment by yokoffing** [comment]
Did you `CTRL`+`F` in Fast/Secure/Pesky and search for `reader.parse-on-load.enabled`?

https://github.com/yokoffing/Betterfox/blob/099fe168bac91b67e493a97b26f9fd4103be1a78/Peskyfox.js#L454-L457

Line 456 should say "disable", but same difference. (I corrected the word in the next update.)
