### ISSUE TITLE
pdfjs.sidebarViewOnLoad incorrect documentation in Peskyfox.js

### ISSUE THREAD

**Issue by Lordiun** [yokoffing/Betterfox#246]
Just wanted to make you aware the comments in peskyfox states that -1 is disabled while in reality it is actually remember previous state and 0 is disabled. So something like below would be more accurate. Thank you for your work

// PREF: PDF sidebar on load [HIDDEN] 
// 2=table of contents (if not available, will default to 1)
// 1=view pages
// 0=disabled
// -1=remember previous state

**Comment by yokoffing** [comment]
Thank you! This will be fixed in the next release!
