### ISSUE TITLE
Set "widget.gtk.hide-pointer-while-typing.enabled" to false

### ISSUE THREAD

**Issue by ItsProfessional** [yokoffing/Betterfox#248]
On firefox 119 and newer, firefox has made the cursor automatically hide when typing on linux. This, should NOT be handled by firefox. This is handled by the window manager. Different desktop environments and window managers provide ways of doing this through a config option. In this version, they also made the cursor hide if the option is enabled in windows settings, which is fair, because windows only respects that setting in their own win32 dialogs, and firefox didn't respect it earlier on windows. But on linux, that is not necessary. This config option doesn't affect Windows.

**Comment by yokoffing** [comment]
https://github.com/yokoffing/Betterfox/commit/3086c8bccb30d966832046bd877c1bb0b3f6c2a2

**Comment by yokoffing** [comment]
Looks like there's others, too:

- pref("widget.gtk.rounded-bottom-corners.enabled", false);
- pref("widget.windows.titlebar-accent.enabled", false);

**Comment by ItsProfessional** [comment]
Interesting. `widget.windows.titlebar-accent.enabled` should probably not be set by this project, as (I think) it only does that if configured in windows settings, which is intended behaviour.
