### ISSUE TITLE
Twitch not working?

### ISSUE THREAD

**Issue by sxarthur** [yokoffing/Betterfox#250]
Don't know if it's actually a bug, but seems like twitch stopped working(unsupported browser) and error #4000

**Comment by iam-py-test** [comment]
Are you able to reproduce the issue in a new profile with only BetterFox?
Thanks

**Comment by yokoffing** [comment]
GitHub itself is having issues right now, so there may be widespread server or CDN issues.

please use the proper form is the issue persists: https://github.com/yokoffing/Betterfox/issues/new?assignees=yokoffing&labels=&projects=&template=bug_report.md&title=
