### ISSUE TITLE
Youtube player doesn't work

### ISSUE THREAD

**Issue by nordgladius** [yokoffing/Betterfox#251]
when I download and used the betterfox all things are working fine but when I try to watch a youtube video it doesn't play. the loading circle keeps spinning. what do I do ?

**Comment by iam-py-test** [comment]
Would you mind filling out the issue form in order to narrow down the issue?
Thank you.

**Comment by yokoffing** [comment]
In the future, please use the proper form: https://github.com/yokoffing/Betterfox/issues/new?assignees=yokoffing&labels=&projects=&template=bug_report.md&title=

Please read:
* https://www.ghostery.com/blog/whats-happening-with-youtube-ads
* https://www.reddit.com/r/uBlockOrigin/comments/17j6ygs/youtube_antiadblock_and_ads_october_29_2023_mega/
* https://community.brave.com/t/psa-youtube-adblock-detection/510337
