### ISSUE TITLE
Sites not rendering correctly

### ISSUE THREAD

**Issue by limaceous-bushwhacker** [yokoffing/Betterfox#254]
## BEFORE YOU BEGIN
I have attempted the following troubleshooting suggestions:
- [x] The issue persists when using Firefox in [Troubleshoot Mode](https://support.mozilla.org/en-US/kb/diagnose-firefox-issues-using-troubleshoot-mode).
- [x] Disabled DNS-level content blocking (AdGuard Home, NextDNS, Control D, RethinkDNS, PiHole, etc), [cleared my DNS cache](https://www.pcmag.com/how-to/how-to-flush-your-dns-cache), and used my ISP's DNS resolver (if applicable).
- [x] [Cleared website data](https://support.mozilla.org/en-US/kb/clear-cookies-and-site-data-firefox), restarted Firefox, and my issue persists.
- [x] I have created a [new profile](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles). The issue persists when using the current [user.js](https://github.com/yokoffing/Betterfox/blob/master/user.js) file on GitHub. (Must be in a new profile and a new user.js!)

## REPORT
**Describe the bug**
I am experiencing rendering issues on certain websites, specifically casioindiashop.com and github.com, when using the user.js configuration file in Firefox 116.0.3. The problem does not occur when the user.js file is not applied.

**To Reproduce**
1. Open Firefox with the user.js configuration file applied.
2. Navigate to [casioindiashop.com](https://casioindiashop.con)
3. Observe rendering issues on the website.
4. Navigate to [github.com](https://github.com)
5. Observe rendering issues on the GitHub website.

**Expected behavior**
The websites, casioindiashop.com and github.com, should render correctly with the user.js configuration file applied, as they do without the configuration.

**Screenshots**
Screenshots have been attached to illustrate the rendering issues on both websites.
1. Screenshot_casioindiashop.png: This screenshot shows the rendering issue on casioindiashop.com. 
![Screenshot_casioindiashop.png](https://github.com/yokoffing/Betterfox/assets/67668779/df802b0e-6b25-4592-b6ad-9fac8e716054)

2. Screenshot_github.png: This screenshot shows the rendering issue on github.com.
![Screenshot_github.png](https://github.com/yokoffing/Betterfox/assets/67668779/43244f59-c8cf-4a41-a4b3-3ec68fbc5615)

**Desktop (please complete the following information):**
 - OS: Pop!_OS 22.04 LTS
 - Browser: Firefox
 - Version: 116.0.3 64-bit

**Additional context**
I have observed that on GitHub, the rendering issue can be temporarily resolved by refreshing the page. After refreshing, the website works fine until the next navigation. This suggests that the problem may be related to a dynamic aspect of the page loading process.

**Comment by yokoffing** [comment]
`https://www.casioindiashop.com` is broken on Safari as well, but it is loading for me on Chrome and vanilla Firefox, so this needs investigating.

**Comment by yokoffing** [comment]
@limaceous-bushwhacker  `https://www.casioindiashop.com/` is working for me today on all browsers. Can you check this in Firefox using Betterfox in both normal window and [private window](https://support.mozilla.org/en-US/kb/private-browsing-use-firefox-without-history#w_how-do-i-open-a-new-private-window)?
