### ISSUE TITLE
Firefox View not disabled but looks like it should be

### ISSUE THREAD

**Issue by BourbonCrow** [yokoffing/Betterfox#255]
## BEFORE YOU BEGIN
I have attempted the following troubleshooting suggestions:
- [x] The issue persists when using Firefox in [Troubleshoot Mode](https://support.mozilla.org/en-US/kb/diagnose-firefox-issues-using-troubleshoot-mode).
- [x] Disabled DNS-level content blocking (AdGuard Home, NextDNS, Control D, RethinkDNS, PiHole, etc), [cleared my DNS cache](https://www.pcmag.com/how-to/how-to-flush-your-dns-cache), and used my ISP's DNS resolver (if applicable).
- [x] [Cleared website data](https://support.mozilla.org/en-US/kb/clear-cookies-and-site-data-firefox), restarted Firefox, and my issue persists.
- [x] I have created a [new profile](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles). The issue persists when using the current [user.js](https://github.com/yokoffing/Betterfox/blob/master/user.js) file on GitHub. (Must be in a new profile and a new user.js!)

## REPORT
Not sure if i wanna call this a bug or not but in common overides there is the code below to restore Firefox View but in the dowloaded 118 version of the code there is no disabling of browser.tabs.firefox-view-next. it only disables browser.tabs.firefox-view and due to that the Firefox view is never disabled in FF119+ by running the downloaded user.js
```
// PREF: restore Firefox View
user_pref("browser.tabs.firefox-view", true);
user_pref("browser.tabs.firefox-view-next", true); // [FF119+]
```

**To Reproduce**
```
1. fresh profile
2. load in the downloaded user.js
```

**Expected behavior**
I assume the firefox view is supposed to be disabled by default since the common overide to enable it also 1 of the 2 are disabled in the user.js

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox 119.0 64bit
 - Version: 118

**Comment by yokoffing** [comment]
> the code below to restore Firefox View but in the dowloaded 118 version of the code there is no disabling of `browser.tabs.firefox-view-next`. it only disables `browser.tabs.firefox-view` and due to that the Firefox view is never disabled in FF119+

Thanks for reporting. That's because the current `user.js` is v.118, not for v.119.

This section will be removed once our v.119 is released. Sync will no longer be disabled by default. Also, disabling Sync is updated already in [Optional Hardening](https://github.com/yokoffing/Betterfox/wiki/Optional-Hardening#firefox-sync--view).
