### ISSUE TITLE
Shortcuts Disappear after closing and reopening Firefox

### ISSUE THREAD

**Issue by Batlez** [yokoffing/Betterfox#259]
## REPORT
**Describe the bug**
Shortcuts don't save to home screen after I close and reopon Firefox

**To Reproduce**
*Steps to reproduce the behavior:*

Not really sure, I just installed user.js and it started happening

**Expected behavior**
*A clear and concise description of what you expected to happen.*

I should see my shortcuts after I enabled them. After closing and reopening Firefox, they disappear again.
**Screenshots**
*If applicable, add screenshots to help explain your problem.*
![image](https://github.com/yokoffing/Betterfox/assets/63690709/3c6809dc-7326-4a49-86a6-0eedb56c1cd3)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox
 - Version: 119.0.1

**Additional context**
*Add any other context about the problem here.*

**Comment by yokoffing** [comment]
Please read https://github.com/yokoffing/Betterfox#getting-started

Review https://github.com/yokoffing/Betterfox/wiki/Common-Overrides#new-tab-shortcuts

**Comment by Batlez** [comment]
Thank you for your help. I changed this to true:

user_pref("browser.newtabpage.activity-stream.feeds.topsites", true);
