### ISSUE TITLE
Add additional tracking protection for x.com

### ISSUE THREAD

**Issue by Nitrousoxide** [yokoffing/Betterfox#263]
Currently securefox lists *.twitter.com as a tracking url to block.  However since x.com is also now a valid url to visit twitter, and many sites are switching over to this url for their api's *.x.com should also be added, assuming it doesn't break something.

**Comment by yokoffing** [comment]
@Ilomantis is correct.

https://github.com/yokoffing/Betterfox/blob/1653fc90140e398c660093b512428c0a470c3a09/Securefox.js#L55-L63

As far as I've seen, everything is still directed through `twitter.com`. I haven't seen any embedded tweets via `x.com`.

Feel free to re-open if you find a site that does.
