### ISSUE TITLE
browser.contentblocking.category=strict breaks various websites

### ISSUE THREAD

**Issue by webstrand** [yokoffing/Betterfox#264]
## BEFORE YOU BEGIN
I have attempted the following troubleshooting suggestions:
- [ ] The issue persists when using Firefox in [Troubleshoot Mode](https://support.mozilla.org/en-US/kb/diagnose-firefox-issues-using-troubleshoot-mode).
- [x] Disabled DNS-level content blocking (AdGuard Home, NextDNS, Control D, RethinkDNS, PiHole, etc), [cleared my DNS cache](https://www.pcmag.com/how-to/how-to-flush-your-dns-cache), and used my ISP's DNS resolver (if applicable).
- [x] [Cleared website data](https://support.mozilla.org/en-US/kb/clear-cookies-and-site-data-firefox), restarted Firefox, and my issue persists.
- [x] I have created a [new profile](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles). The issue persists when using the current [user.js](https://github.com/yokoffing/Betterfox/blob/master/user.js) file on GitHub. (Must be in a new profile and a new user.js!)

## REPORT
**Describe the bug**
Visiting <https://www.google.com/maps/place/mongolia/data=!4m2!3m1!1s0x3627050669aa6d4b:0xe0dd213937e6e096?sa=X&ved=2ahUKEwiCx9DS5-6CAxWAk4kEHQg9DAMQ8gF6BAgREAA> causes the tab to lock up.

**To Reproduce**
*Steps to reproduce the behavior:*

```
1. Create a new profile
2. Install user.js
3. Visit <https://www.google.com/maps/place/mongolia/data=!4m2!3m1!1s0x3627050669aa6d4b:0xe0dd213937e6e096?sa=X&ved=2ahUKEwiCx9DS5-6CAxWAk4kEHQg9DAMQ8gF6BAgREAA>
4. Observe that the tab is non-responsive
```

**Expected behavior**
The tab should not lock up like this

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 120.0

**Additional context**
I bisected `user.js` to find the offending preference, and I found that if I remove `user_pref("browser.contentblocking.category", "strict")` from `user.js` and create a new profile (you _must_ restart firefox after changing this value) that map page no longer becomes non-responsive.

Various other pages become inconsistently non-responsive, that maps link is the only one that's consistent.

**Comment by yokoffing** [comment]
I cannot reproduce on Stable or Nightly with Windows 11. I don't have access to a Linux build at the moment, so this may be a Linux-only bug. But that's a pretty serious bug for Mozilla if **Strict** is causing that behavior.

There was an issue awhile back with Google Maps caused by WebGL https://github.com/yokoffing/Betterfox/issues/203.

Have you updated to [120.0.1](https://www.mozilla.org/en-US/firefox/120.0.1/releasenotes/)?
> Fixed an issue that was causing 100% CPU usage on sites such as Google Maps. ([bug 1866409](https://bugzilla.mozilla.org/show_bug.cgi?id=1866409))

**Comment by webstrand** [comment]
Yep, upgrading to 120.0.1 does indeed fix the issue.
