### ISSUE TITLE
Remove NextDNS referral ID or mention sponsored link

### ISSUE THREAD

**Issue by maclermo** [yokoffing/Betterfox#266]
https://github.com/yokoffing/Betterfox/blob/396a465b73af957855092fa6a423572125ee33f8/README.md?plain=1#L28

**Comment by maclermo** [comment]
It's not that it's a critical issue, it's just that this is basic _Netiquette_.

You should let people decide how they want to encourage you financially.

**Comment by yokoffing** [comment]
That's fair. https://github.com/yokoffing/Betterfox/commit/042bcc1c56537c61c6df5e2b00309433ce4d16e1
