### ISSUE TITLE
browser.download.useDownloadDir

### ISSUE THREAD

**Issue by hub2git** [yokoffing/Betterfox#267]
Dear dev yokoffing,
I am using your betterfox creation. Thank you for your work on that . My fave browser is now more secure.

 In the Peskyfox section there is this line:

` user_pref("browser.download.useDownloadDir", false);`

Why? Isn't being asked always where to save the pesky choice? In other words, isn't it less pesky for the line above to say "true"?

The description of Peskyfox (in https://github.com/yokoffing/BetterFox#simple-configs) says:  "Provide a clean, distraction-free browsing experience."

Isn't being always asked where to save a download distraction-_full_?

My entire user.js is at https://gist.github.com/hub2git/0076fa1464e9c3ffd73839a6e6b2182d

**Comment by yokoffing** [comment]
You're not wrong. The pref `browser.download.useDownloadDir` was added for security, but I'm happy to revisit it.

https://github.com/yokoffing/Betterfox/blob/f269678337a15e24b94fa02dcc2e39b56d89936d/Peskyfox.js#L322-L339

We currently have settings that prioritizes security and users who prefer to download in various locations.

A build that balances annoyances and security may be:
```javascript
user_pref("browser.download.useDownloadDir", true); // DEFAULT
user_pref("browser.download.always_ask_before_handling_new_types", true);
```

This way Firefox saves common files without unneeded interaction (`Content Type`), but alerts the user for first-time file types or unlisted types (`What should Firefox do with other files?`), like ZIP files.

![Screenshot 2023-12-20 091431](https://github.com/yokoffing/Betterfox/assets/11689349/1cc042c0-d403-4dd2-97de-7a54b551bad2)
