### ISSUE TITLE
Google account login pop up not working 

### ISSUE THREAD

**Issue by AdrianFerrer1** [yokoffing/Betterfox#270]
## BEFORE YOU BEGIN
I have attempted the following troubleshooting suggestions:
- [] The issue persists when using Firefox in [Troubleshoot Mode](https://support.mozilla.org/en-US/kb/diagnose-firefox-issues-using-troubleshoot-mode).
- [?] Disabled DNS-level content blocking (AdGuard Home, NextDNS, Control D, RethinkDNS, PiHole, etc), [cleared my DNS cache](https://www.pcmag.com/how-to/how-to-flush-your-dns-cache), and used my ISP's DNS resolver (if applicable).
- [x] [Cleared website data](https://support.mozilla.org/en-US/kb/clear-cookies-and-site-data-firefox), restarted Firefox, and my issue persists.
- [x] I have created a [new profile](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles). The issue persists when using the current [user.js](https://github.com/yokoffing/Betterfox/blob/master/user.js) file on GitHub. (Must be in a new profile and a new user.js!)

## REPORT
**Describe the bug**
*A clear and concise description of what the bug is.*

I have tried to add the site on the exceptions manager and it doesn't do anything. Facebook works but Google doesn't, for some reason

**To Reproduce**
*Steps to reproduce the behavior:*

```
1. Go to 'https://www.duolingo.com/?isLoggingIn=true'
2. Click on 'the google icon'
3. See error
```

**Expected behavior**
*A clear and concise description of what you expected to happen.*

Pop up of the account login showing up.

**Desktop (please complete the following information):**
 - OS:Linux
 - Browser:Firefox
 - Version:Latest

**Comment by yokoffing** [comment]
You indicated that the issue doesn't persist in Troubleshoot Mode, meaning it is likely an extension causing the behavior. Have you ruled those out?
