### ISSUE TITLE
Facebook Login isn't saved

### ISSUE THREAD

**Issue by casualbugs** [yokoffing/Betterfox#272]
Using Firefox 121.01

Have disabled all addons. I can't figure out which betterfox setting is causing this but my Facebook login sessions aren't remembered.

Every time after re-opening the browser, I have to login to Facebook again. Any idea which override I should be using?

**Comment by Kyazs** [comment]
> Most likely https://github.com/yokoffing/Betterfox/wiki/Optional-Hardening#sanitize-on-close

i already remove the pref. i already also disabled the clear ache/cookies on close in settings. but the problem stills persists. i cant exactly figure out why..

**Comment by yokoffing** [comment]
I tested on a new Firefox profile with the latest user.js. No issues with Facebook account persisting between sessions.

- Go to ☰ → Settings → Privacy & Security → Cookies and Site Data → Manage Exceptions → add `https://facebook.com`
- Are you using any DNS filtering? Anything going on there?

If you followed the steps [here](https://github.com/yokoffing/Betterfox#getting-started), then you should have a backup profile to revert to. But if you don't, you can make a new profile and migrate most things from your old profile (see [here](https://github.com/yokoffing/Betterfox/issues/180#issuecomment-1622113788)).

**Comment by Kyazs** [comment]
> I tested on a new Firefox profile with the latest user.js. No issues with Facebook account persisting between sessions.
> 
>     * Go to ☰ → Settings → Privacy & Security → Cookies and Site Data → Manage Exceptions → add `https://facebook.com`
> 
>     * Are you using any DNS filtering? Anything going on there?
> 
> 
> If you followed the steps [here](https://github.com/yokoffing/Betterfox#getting-started), then you should have a backup profile to revert to. But if you don't, you can make a new profile and migrate most things from your old profile (see [here](https://github.com/yokoffing/Betterfox/issues/180#issuecomment-1622113788)).

i already add the facebook.com in my exceptions. both inside the firefox and the dns filtering (im using NextDns). i dont want to reach the point of having to revert things back again.. is there other options? if not i got no choice..

**Comment by Kyazs** [comment]
p.s 
but the weird thing is. this only happens on facebook only. The rest of the websites are ok

**Comment by yokoffing** [comment]
> I am using uBlock origin with the recommended filteres

I would ask for which ones specifically, but I don't think uBO filters apply to this issue.

> After a day or so
> Visit facebook.com > login > asked to verify browser (no 2FA) > close/reopen firefox > login doesn't persist.
> the weird thing is. this only happens on facebook only.

Could this be because of 2FA? (I don't have 2FA active on my test FB account.) Perhaps FB requires you to login again when you have additional security settings activate (like 2FA).

For sites (like email) that I have 2FA active, it is very common for me to have to re-enter my credentials after 24 hours.

**Comment by yokoffing** [comment]
> Adding facebook to exceptions works. 

So, https://github.com/yokoffing/Betterfox/issues/272#issuecomment-1889542829

> Couldn't find what causes this.

The pref `privacy.sanitize.sanitizeOnShutdown`.

https://github.com/yokoffing/Betterfox/blob/4d23050c740d6b773aedaf3c659166e64447fdd5/Securefox.js#L452-L460

**Comment by yokoffing** [comment]
AFAIK, exceptions only applies to `privacy.sanitize.sanitizeOnShutdown`.
