### ISSUE TITLE
Crunchyroll issues

### ISSUE THREAD

**Issue by zero5enpai** [yokoffing/Betterfox#277]
## BEFORE YOU BEGIN
I have attempted the following troubleshooting suggestions:
- [x] The issue persists when using Firefox in [Troubleshoot Mode](https://support.mozilla.org/en-US/kb/diagnose-firefox-issues-using-troubleshoot-mode).
- [x] Disabled DNS-level content blocking (AdGuard Home, NextDNS, Control D, RethinkDNS, PiHole, etc), [cleared my DNS cache](https://www.pcmag.com/how-to/how-to-flush-your-dns-cache), and used my ISP's DNS resolver (if applicable).
- [x] [Cleared website data](https://support.mozilla.org/en-US/kb/clear-cookies-and-site-data-firefox), restarted Firefox, and my issue persists.
- [x] I have created a [new profile](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles). The issue persists when using the current [user.js](https://github.com/yokoffing/Betterfox/blob/master/user.js) file on GitHub. (Must be in a new profile and a new user.js!)

## REPORT
**Website image/stream breaking**
Certain images wont load (user profile pictures and slideshow pictures) and no stream will load. (video player wont appear)

**To Reproduce**
*Steps to reproduce the behavior:*

1. Go to [crunchyroll](https://www.crunchyroll.com/) (slideshow images wont load)
![firefox_HWgSVxqiCC](https://github.com/yokoffing/Betterfox/assets/40106969/685bcbf6-b473-4393-8c15-9130cfed4e28)
2. Go to any free stream [example](https://www.crunchyroll.com/watch/GEVUZDV1M/crimson-is-the-sound-of-dawn) (player wont load)
![firefox_ruYjexVdKH](https://github.com/yokoffing/Betterfox/assets/40106969/43fd7bd2-1318-429e-b41d-a4507a2308dd)
3. Scroll down to see the comments (user profiles wont load)
![firefox_c6x55wctum](https://github.com/yokoffing/Betterfox/assets/40106969/4cb0155b-6bc3-487f-91d1-75082cce7876)

**Expected behavior**
I would expect the website to load properly

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Version 124.0b3 (64-bit)
 - Version: (Betterfox) 122

**Additional context**
I'm currently using defaults from Securefox, Peskyfox and as override: `user_pref("identity.fxaccounts.enabled", true);`

What I already did and why I dont know what to do:
1. Website broke on old profile and it couldnt be fixed even by deleting the old user.js and prefs.js (Other (Default) Profiles still worked)
2. Creating a new profile with the same user.js broke it as well but made it fixable by removing some tracking protection values from securefox. (yes I removed prefs.js eacht time I troubleshooted)
3. After some time it broke again and wasnt fixable like the first profile but there is a temporary workaround (which also just works sometimes):

**Steps:**
1. Visit a broken stream page like the one shown above
2. Go to Firefox privacy settings and switch from strict to standard (!or the other way around!) and click on "refresh all tabs"
3. Go back to the crunchyroll stream, the website should reload automatically and the stream as well as image loading will work!
4. Refresh the page once again and it will be broken again.
Adding crunchyroll to the enhanced ztacking protection exception in firefox wont help either.

**Comment by zero5enpai** [comment]
Could someone approve that its not a local issue?

**Comment by zero5enpai** [comment]
It should be the only override which interacts with Firefoxes behavior. 
Beside that override I have some Theme overrides:

```
//
// Theme
//

// smaller search engine suggestion prompt
user_pref("browser.urlbar.update1", false);

// show compact mode option in GUI
user_pref("browser.compactmode.show",	true);

// hide vpn banner
user_pref("browser.contentblocking.report.hide_vpn_banner",	true);

// ctrl tab will cycle through recent tabs
user_pref("browser.ctrlTab.sortByRecentlyUsed",	true);

// dark mode display bgcolor set to black
user_pref("browser.display.background_color.dark",	"#000000");

// prevent sudden white flashes in dark mode by disabling this. Might not always work
user_pref("browser.display.use_system_colors",	false);

user_pref("browser.download.panel.shown",	true);

user_pref("browser.engagement.ctrlTab.has-used",	true);

user_pref("browser.engagement.downloads-button.has-used",	true);

user_pref("browser.engagement.fxa-toolbar-menu-button.has-used",	true);

user_pref("browser.engagement.home-button.has-used",	true);

user_pref("browser.engagement.sidebar-button.has-used",	true);

// disable topstories in newtabpage
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories",	false);

// show mozilla snippets info in newtabpage
user_pref("browser.newtabpage.activity-stream.feeds.snippets",	true);

user_pref("browser.newtabpage.activity-stream.section.highlights.includeVisited",	false);

// disable sponsored sites in newtabpage
user_pref("browser.newtabpage.activity-stream.showSponsoredTopSites",	false);

//proton toolbar version
user_pref("browser.proton.toolbar.version",	3);

user_pref("browser.shell.checkDefaultBrowser",	false);

// disable default browser checks
user_pref("browser.shell.defaultBrowserCheckCount",	1);
user_pref("browser.shell.didSkipDefaultBrowserCheckOnFirstRun",	true);

// titlebar off
user_pref("browser.tabs.inTitlebar",	1);

// always show bookmarks bar
user_pref("browser.toolbars.bookmarks.visibility",	"always");

// directly enable Compact Density mode without enabling it in the GUI
user_pref("browser.uidensity",	1);

// enable math calcs in url bar
user_pref("browser.urlbar.suggest.calculator",	true);

//disable topsites view in url bar. This prevents url bar from expanding on mouse click
user_pref("browser.urlbar.suggest.topsites",	false);

// findbar enable highlightall option
user_pref("findbar.highlightAll",	true);

// set default font
user_pref("font.name.serif.x-western",	"Segoe UI Variable Small");
```

Yes I use extensions but they are disabled in Troubleshoot mode and I also get the issues in there

**Comment by zero5enpai** [comment]
thats the blocked player:
![firefox_7LTeCyXwVv](https://github.com/yokoffing/Betterfox/assets/40106969/6b5911e6-b68a-49e9-9490-3abfe8afa377)
and those are the profile pictures:
![firefox_5OkikuTGTS](https://github.com/yokoffing/Betterfox/assets/40106969/14cad469-c2d8-4619-9a3d-5b6ddcbd5505)

**Comment by zero5enpai** [comment]
Just figured how to reset to working state:
1. deleting cookie data for crunchyroll
2. deleting content-prefs.sqlite
3. removing Securefox

**Comment by zero5enpai** [comment]
Securefox content:

```
/** TRACKING PROTECTION ***/
user_pref("browser.contentblocking.category", "strict");
user_pref("urlclassifier.trackingSkipURLs", "*.reddit.com, *.twitter.com, *.twimg.com, *.tiktok.com");
user_pref("urlclassifier.features.socialtracking.skipURLs", "*.instagram.com, *.twitter.com, *.twimg.com");
user_pref("network.cookie.sameSite.noneRequiresSecure", true);
user_pref("browser.download.start_downloads_in_tmp_dir", true);
user_pref("browser.helperApps.deleteTempFileOnExit", true);
user_pref("browser.uitour.enabled", false);
user_pref("privacy.globalprivacycontrol.enabled", true);

/** OCSP & CERTS / HPKP ***/
user_pref("security.OCSP.enabled", 0);
user_pref("security.remote_settings.crlite_filters.enabled", true);
user_pref("security.pki.crlite_mode", 2);

/** SSL / TLS ***/
user_pref("security.ssl.treat_unsafe_negotiation_as_broken", true);
user_pref("browser.xul.error_pages.expert_bad_cert", true);
user_pref("security.tls.enable_0rtt_data", false);

/** DISK AVOIDANCE ***/
user_pref("browser.privatebrowsing.forceMediaMemoryCache", true);
user_pref("browser.sessionstore.interval", 60000);

/** SHUTDOWN & SANITIZING ***/
user_pref("privacy.history.custom", true);

/** SEARCH / URL BAR ***/
user_pref("browser.search.separatePrivateDefault.ui.enabled", true);
user_pref("browser.urlbar.update2.engineAliasRefresh", true);
user_pref("browser.search.suggest.enabled", false);
user_pref("browser.urlbar.suggest.quicksuggest.sponsored", false);
user_pref("browser.urlbar.suggest.quicksuggest.nonsponsored", false);
user_pref("browser.formfill.enable", false);
user_pref("security.insecure_connection_text.enabled", true);
user_pref("security.insecure_connection_text.pbmode.enabled", true);
user_pref("network.IDN_show_punycode", true);

/** HTTPS-FIRST POLICY ***/
user_pref("dom.security.https_first", true);
user_pref("dom.security.https_first_schemeless", true);

/** PASSWORDS ***/
user_pref("signon.formlessCapture.enabled", false);
user_pref("signon.privateBrowsingCapture.enabled", false);
user_pref("network.auth.subresource-http-auth-allow", 1);
user_pref("editor.truncate_user_pastes", false);

/** MIXED CONTENT + CROSS-SITE ***/
user_pref("security.mixed_content.block_display_content", true);
user_pref("security.mixed_content.upgrade_display_content", true);
user_pref("security.mixed_content.upgrade_display_content.image", true);
user_pref("pdfjs.enableScripting", false);
user_pref("extensions.postDownloadThirdPartyPrompt", false);

/** HEADERS / REFERERS ***/
user_pref("network.http.referer.XOriginTrimmingPolicy", 2);

/** CONTAINERS ***/
user_pref("privacy.userContext.ui.enabled", true);

/** WEBRTC ***/
user_pref("media.peerconnection.ice.proxy_only_if_behind_proxy", true);
user_pref("media.peerconnection.ice.default_address_only", true);

/** SAFE BROWSING ***/
user_pref("browser.safebrowsing.downloads.remote.enabled", false);

/** MOZILLA ***/
user_pref("permissions.default.desktop-notification", 2);
user_pref("permissions.default.geo", 2);
user_pref("geo.provider.network.url", "https://location.services.mozilla.com/v1/geolocate?key=%MOZILLA_API_KEY%");
user_pref("permissions.manager.defaultsUrl", "");
user_pref("webchannel.allowObject.urlWhitelist", "");

/** TELEMETRY ***/
user_pref("datareporting.policy.dataSubmissionEnabled", false);
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("toolkit.telemetry.unified", false);
user_pref("toolkit.telemetry.enabled", false);
user_pref("toolkit.telemetry.server", "data:,");
user_pref("toolkit.telemetry.archive.enabled", false);
user_pref("toolkit.telemetry.newProfilePing.enabled", false);
user_pref("toolkit.telemetry.shutdownPingSender.enabled", false);
user_pref("toolkit.telemetry.updatePing.enabled", false);
user_pref("toolkit.telemetry.bhrPing.enabled", false);
user_pref("toolkit.telemetry.firstShutdownPing.enabled", false);
user_pref("toolkit.telemetry.coverage.opt-out", true);
user_pref("toolkit.coverage.opt-out", true);
user_pref("toolkit.coverage.endpoint.base", "");
user_pref("browser.ping-centre.telemetry", false);
user_pref("browser.newtabpage.activity-stream.feeds.telemetry", false);
user_pref("browser.newtabpage.activity-stream.telemetry", false);

/** EXPERIMENTS ***/
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.normandy.enabled", false);
user_pref("app.normandy.api_url", "");

/** CRASH REPORTS ***/
user_pref("breakpad.reportURL", "");
user_pref("browser.tabs.crashReporting.sendReport", false);
user_pref("browser.crashReports.unsubmittedCheck.autoSubmit2", false);

/** DETECTION ***/
user_pref("captivedetect.canonicalURL", "");
user_pref("network.captive-portal-service.enabled", false);
user_pref("network.connectivity-service.enabled", false);
```

**Comment by zero5enpai** [comment]
any clues which setting could effect the content-prefs.sqlite file and block the content?

**Comment by zero5enpai** [comment]
Okay I figured out why it breaks:
The setting `user_pref("privacy.globalprivacycontrol.enabled", true);` is breaking crunchyroll.

**Comment by yokoffing** [comment]
That's really odd if GPC is the source of your break. I wonder if it's region specific.

I would think it's region specific + misconfiguration with Crunchyroll on Firefox.

To test, you could try using Crunchyroll with Brave. They have GPC enabled by default.

**Comment by zero5enpai** [comment]
If Brave is out of the box with GPC it has to be a misconfiguration with Crunchyroll on Firefox. Got no problems on Brave

**Comment by zero5enpai** [comment]
I also tried out to use VPN while troubleshooting and it didnt work either. So region specific shouldnt be the problem as well

**Comment by yokoffing** [comment]
@zero5enpai If you don't mind taking the time, it may be worth reporting on [Bugzilla](https://bugzilla.mozilla.org/enter_bug.cgi).

I would say open a report on [WebCompat](https://webcompat.com/issues/new); but since GPC is not enabled by default, Bugzilla is more appropriate.
