### ISSUE TITLE
Firefox crashes when opening local HTML file (file size > 4MB)

### ISSUE THREAD

**Issue by onmyouji** [yokoffing/Betterfox#279]
## BEFORE YOU BEGIN
I have attempted the following troubleshooting suggestions:
- [x] The issue persists when using Firefox in [Troubleshoot Mode](https://support.mozilla.org/en-US/kb/diagnose-firefox-issues-using-troubleshoot-mode).
- [x] Disabled DNS-level content blocking (AdGuard Home, NextDNS, Control D, RethinkDNS, PiHole, etc), [cleared my DNS cache](https://www.pcmag.com/how-to/how-to-flush-your-dns-cache), and used my ISP's DNS resolver (if applicable).
- [x] [Cleared website data](https://support.mozilla.org/en-US/kb/clear-cookies-and-site-data-firefox), restarted Firefox, and my issue persists.
- [x] I have created a [new profile](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles). The issue persists when using the current [user.js](https://github.com/yokoffing/Betterfox/blob/master/user.js) file on GitHub. (Must be in a new profile and a new user.js!)

## REPORT
**Describe the bug**
Using Betterfox user.js causes Firefox to crash when opening local HTML file. The crash happens if the HTML file is larger than 4MB, smaller file doesn't cause crash.

**To Reproduce**
1. Create a fresh new profile.
2. Open a local HTML file that is bigger than 4MB. You can [download this HTML file to your computer](https://www.mediafire.com/file/ipmu7ugrd2vvelr/LICENSES.chromium.html.zip/file) or use your own HTML file (> 4MB).
3. File will open normally.
4. Close Firefox, then put [the user.js file](https://raw.githubusercontent.com/yokoffing/Betterfox/main/user.js) to your profile folder.
5. Load Firefox, then open the local HTML file from your computer.
6. Your tab will crash and you get message "Gah. Your tab just crashed."

**Expected behavior**
Firefox should not crash when opening a local HTML file from your computer.

**Screenshots**
![2024-03-12_184834](https://github.com/yokoffing/Betterfox/assets/8424198/8f363b50-803d-425e-809b-5e2ab34a3a49)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 64-bit Version 22H2 (19045.4046)
 - Browser: Firefox
 - Version: 123.0.1

**Comment by yokoffing** [comment]
I can reproduce.

Apparently this is happening in Waterfox as well:
* https://github.com/WaterfoxCo/Waterfox/issues/3254
* https://www.reddit.com/r/waterfox/comments/1aq7fgb/waterfox_tab_crashes_when_loading_an_html_file/

**Comment by yokoffing** [comment]
It’ll close once I push a release tomorrow.
