### ISSUE TITLE
Applying Fastfox.js

### ISSUE THREAD

**Issue by Broken-Glass1** [yokoffing/Betterfox#281]
If I put Fastfox.js into the root folder of profile it does not working. Only user.js working. But I only want to use Fastfox.js. How resolve this issue ?

**Comment by Feejus** [comment]
Hello, I recently discovered Betterfox and took some time to delve into user.js and prefs.js.

The prefs.js file is automatically created and holds all custom settings from the previous session's end. Meanwhile, the user.js file, which is manually created, is read last during startup, after prefs.js. This means that any settings specified in user.js will override those in other preference files.

So, if you're only interested in using Fastfox.Js, simply rename the file to user.js.

I hope this helps!

**Comment by Feejus** [comment]
Thank you for your response. Could you please elaborate on what you mean by "it did not help"? I want to ensure I fully understand the issue you are facing.

Based on the steps you mentioned:

    You opened both user.js and prefs.js files.
    You compared the settings in user.js with those in prefs.js, and they were NOT identical?

However, if the settings in user.js and prefs.js are identical and you are still experiencing issues with Firefox, it would be helpful if you could clarify the following:

    Are you encountering any specific problems or unexpected behaviour in Firefox after making the changes in user.js?
    What were your expectations or desired outcomes from the changes made in user.js?

The point is that the settings in user.js will be copied over to prefs.js. You can afterward change the same settings in "About:config". 

Thnx

**Comment by Feejus** [comment]
I think you did meantion this in your original post. 

1. you take a backup of your current settings. (When Firefox is closed, copy all files in the profiles folder to a different location). 

2. copy Fastfox.js into the profile folder

3. rename the user.js 

4. now start firefox again 


this should in theory copy across to your prefs.js. 

If this does not work, please go ahead and create a new file called user.js and paste the content of fastfox.js into the user.js file. 

If this does not work, it could be some error I the file it self, see if the user.js from this site work for you?

Thanx

**Comment by yokoffing** [comment]
> gfx.webrender.all

@Broken-Glass1 You need to remove the `//` at the beginning of the pref.

**Comment by Feejus** [comment]
Yes the "//" is a text marker.

**Comment by yokoffing** [comment]
@Broken-Glass1 Please read https://kb.mozillazine.org/User.js_file.

Prefs with `//` are commented out, but you can remove them beside a pref to make it active. It’s not advised to do it for all prefs. I have certain ones commented out for a reason.

**Comment by yokoffing** [comment]
@Broken-Glass1 

> @Feejus if you're only interested in using Fastfox.Js, simply rename the file to user.js.
