### ISSUE TITLE
How to integrate Smoothfox into user.js ?

### ISSUE THREAD

**Issue by wealstarr** [yokoffing/Betterfox#284]
Hello,

I read the description carefully and have modified the script based on my preferences. One thing I can't figure out, what do I do with Smoothfox.js ? Should I just copy it in Profile folder and point the user.js in it's direction or copy the contents of Smoothfox.js into user.js ?

Any help will be greatly appreciated

Kind regards

**Comment by Feejus** [comment]
I had a similar question regarding the integration of SmoothFox settings into the user.js file. From my understanding, you need to locate the relevant settings in the smootherfox.js file and copy them into the "smoothfox" section of your user.js file.

Upon closer inspection, the smootherfox.js file contains specific settings for 120Hz and 90Hz refresh rates. Depending on the capabilities of your monitor and your desired configuration, you can copy the appropriate settings from smootherfox.js and paste them into the user.js file.

This approach allows you to customize the Firefox settings based on the SmoothFox project's recommendations while tailoring them to your specific hardware and preferences.

I hope this explanation helps clarify the process.

**Comment by yokoffing** [comment]
Copy the contents of Smoothfox.js into user.js.

https://github.com/yokoffing/Betterfox/discussions/283#discussioncomment-8976363
