### ISSUE TITLE
Dark mode settings revert to automatic after every restart

### ISSUE THREAD

**Issue by wealstarr** [yokoffing/Betterfox#285]
Hello,

The website appearance setting in the Firefox:
![Capture](https://github.com/yokoffing/Betterfox/assets/26643729/9fd6cc54-e516-4640-9ebb-299138a782b7)

I change it to dark mode but every time I start a new browser session, it reverts to automatic. I reverted to the profile I backed up and the setting sticks. I looked into user.js to see if I can find anything that could pertain to this specific setting so that I can change it permanently but unable to do so.

Which setting in user.js should I change to make it stick to the dark more ? will any kind soul points it out to me ?

Any help will be greatly appreciated.

**Comment by yokoffing** [comment]
https://github.com/yokoffing/Betterfox/blob/c36643914571d10b45f863e3916441071b838ae3/Peskyfox.js#L93-L100

Add `user_pref("layout.css.prefers-color-scheme.content-override", 0);` to your Overrides section of the user.js.
