### ISSUE TITLE
Downloads without prompt

### ISSUE THREAD

**Issue by wealstarr** [yokoffing/Betterfox#286]
Hello,

Before integrating Betterfox, Firefox use to just download the files in the designated folder without prompting me. Now when I click the download link, it first prompts me up and when I click OK, than the download starts.

I tried living with it but it's just too many files too often. Anyone knows what do I have to change to make Firefox download the files without showing a prompt ?

Any help will be greatly appreciated.

**Comment by yokoffing** [comment]
See https://github.com/yokoffing/Betterfox/issues/267#issuecomment-1864575868

**Comment by wealstarr** [comment]
After some searching and trial and error, I was able to locate the setting that controlled the behavior

Line 219
user_pref("browser.download.always_ask_before_handling_new_types", true);

I override it with false, tested and now it seems to download files without prompts.

This is completed. Many thanks to @yokoffing for doing this awesome work and making our lives easy and secure.
