### ISSUE TITLE
Smoothfox.js - parse error quick fix

### ISSUE THREAD

**Issue by MarcusHoltz** [yokoffing/Betterfox#287]
## REPORT

**Describe the bug**

Using Smoothfox.js you may get `prefs parse error: unexpected character` printed to your terminal.

* * *

**To Reproduce**

This affects anything with a decimal point under:  OPTION: NATURAL SMOOTH SCROLLING V3 [MODIFIED] 
(lines 58, 60, 61) in Smoothfox.js

* * *

**Solution** 

Use whole numbers without any decimals. 

* * *

**Example**

Here are the original lines 58-61:

```
user_pref("general.smoothScroll.msdPhysics.slowdownMinDeltaRatio", 2.0);
user_pref("general.smoothScroll.msdPhysics.slowdownSpringConstant", 250);
user_pref("general.smoothScroll.currentVelocityWeighting", 1.0);
user_pref("general.smoothScroll.stopDecelerationWeighting", 1.0);
```

Here are lines 58-61, with no decimal point:

```
user_pref("general.smoothScroll.msdPhysics.slowdownMinDeltaRatio", 2);
user_pref("general.smoothScroll.msdPhysics.slowdownSpringConstant", 250);
user_pref("general.smoothScroll.currentVelocityWeighting", 1);
user_pref("general.smoothScroll.stopDecelerationWeighting", 1);
```

* * *

**Resolution**

With this change, I am no longer receiving an error in my terminal.

* * * 

**Desktop (please complete the following information):**
 - OS: Fedora 39
 - Browser: Firefox 
 - Version: 124.0

**Comment by yokoffing** [comment]
Thanks for reporting! This will be fixed once the new update releases.
