### ISSUE TITLE
Is there a way to re-enable pocket?

### ISSUE THREAD

**Issue by heliophane** [yokoffing/Betterfox#289]
Hello all,

I really like betterfox for the speed increases it gives me, but I actually like to use pocket. Is there a way to re-enable the pocket button? I checked the customize interface menu but it wasn't present. Is there a way to re-enable the button?

**Comment by yokoffing** [comment]
Add these prefs to the bottom of your user.js, where it says `MY OVERRIDES`:

```JAVASCRIPT
user_pref("extensions.pocket.enabled", true);
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories", true);
```

You can find them at:
https://github.com/yokoffing/Betterfox/blob/c36643914571d10b45f863e3916441071b838ae3/user.js#L215-L216

https://github.com/yokoffing/Betterfox/blob/c36643914571d10b45f863e3916441071b838ae3/Peskyfox.js#L310-L315

https://github.com/yokoffing/Betterfox/blob/c36643914571d10b45f863e3916441071b838ae3/Peskyfox.js#L286-L287

**Comment by heliophane** [comment]
Thank you!!!

**Comment by yokoffing** [comment]
FYI https://support.mozilla.org/en-US/kb/future-of-pocket
