### ISSUE TITLE
Smoothfox upgrade: AveYo's Natural Scrolling v4? Why are we still on v3?

### ISSUE THREAD

**Issue by uwidev** [yokoffing/Betterfox#291]
@AveYo has a [v4 for smooth scrolling](https://github.com/AveYo/fox/blob/main/Natural%20Smooth%20Scrolling%20for%20user.js) that was released on 2022. Was there any specific reason why it wasn't merged and stuck on v3?

edit - It seems that copying and pasting it into Betterfox's `SMOOTHFOX` section results in nothing being smooth. An empty `user.js` with v4 seems to work just fine. Currently trying to investigate why it breaks with Betterfox's default configs, but help would be nice.

edit2 - For smooth scrolling to work, make sure you enable Firefox's `Use Smooth Scrolling` setting. I deleted my `prefs,js` to get fresh preferences for `user.js` to apply, but it ended up reverting that setting, hence why things _broke_. Nothing is broken and v4 seems to work just fine.

**Comment by yokoffing** [comment]
> AveYo has a [v4 for smooth scrolling](https://github.com/AveYo/fox/blob/main/Natural%20Smooth%20Scrolling%20for%20user.js) that was released on 2022. Was there any specific reason why it wasn't merged and stuck on v3?

Very opinionated: I didn't like the v3 changes.

> It seems that copying and pasting it into Betterfox's SMOOTHFOX section results in nothing being smooth. An empty user.js with v4 seems to work just fine. Currently trying to investigate why it breaks with Betterfox's default configs, but help would be nice.

Copy+paste your user.js below. Likely missing a character somewhere, or something is accidentally commented out.

> For smooth scrolling to work, make sure you enable Firefox's Use Smooth Scrolling setting. I deleted my prefs,js to get fresh preferences for user.js to apply, but it ended up reverting that setting, hence why things broke. Nothing is broken and v4 seems to work just fine.

Smooth Scrolling is on by default.

**Comment by uwidev** [comment]
> Very opinionated: I didn't like the v3 changes.

You don't like the changes in v3, or from v3 to v4? And if that's the case, what was your reasoning? You could link to a previous discussion if I somehow missed it.

**Comment by yokoffing** [comment]
@uwidev There was no discussion. You can use it if you like v4 better.
