### ISSUE TITLE
Disqus in "Strict" mode doesn't work

### ISSUE THREAD

**Issue by DoTrONoL** [yokoffing/Betterfox#293]
## BEFORE YOU BEGIN
I have attempted the following troubleshooting suggestions:
- [ ] The issue persists when using Firefox in [Troubleshoot Mode](https://support.mozilla.org/en-US/kb/diagnose-firefox-issues-using-troubleshoot-mode).
- [x] Disabled DNS-level content blocking (AdGuard Home, NextDNS, Control D, RethinkDNS, PiHole, etc), [cleared my DNS cache](https://www.pcmag.com/how-to/how-to-flush-your-dns-cache), and used my ISP's DNS resolver (if applicable).
- [x] [Cleared website data](https://support.mozilla.org/en-US/kb/clear-cookies-and-site-data-firefox), restarted Firefox, and my issue persists.
- [x] I have created a [new profile](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles). The issue persists when using the current [user.js](https://github.com/yokoffing/Betterfox/blob/master/user.js) file on GitHub. (Must be in a new profile and a new user.js!)

## REPORT
**Describe the bug**
I want to see Discus comment section in any website that I open when I'm in "strict" mode in `about:preferences#privacy`, but I can't see it.
When I use this settings: `user_pref("browser.contentblocking.category", "standard");` It does work properly, as expected, but I don't want to use "standard" mode, I want to keep it in "strict". I know that I can make a exception and I have tried, but every iteration didn't work properly. Only when I changed content blocking to "standard".

This is what I tried in MY OVERRIDES:
```js
user_pref("urlclassifier.trackingSkipURLs", "*.disqus.com, *.disquscdn.com, *.reddit.com, *.twitter.com, *.twimg.com, *.tiktok.com");
user_pref("urlclassifier.features.socialtracking.skipURLs", "*.disqus.com, *.disquscdn.com, *.instagram.com, *.twitter.com, *.twimg.com");
```

As I could not fix by myself, I'm asking for help.

Example Website: [AMD launches EPYC 4004 CPUs on AM5 package: up to 16 Zen4 cores & 3D V-Cache for $699 - VideoCardz.com](https://videocardz.com/newz/amd-launches-epyc-4004-cpus-on-am5-package-up-to-16-zen4-cores-3d-v-cache-for-699)

**To Reproduce**
*Steps to reproduce the behavior:*

```
1. Go to any website that uses Disqus
2. Scroll to the bottom of the site
3. You see that comment section doesn't appear OR It says (if you keep "strict" value): "Disqus seems to be taking longer than usual. Reload?"
```

**Expected behavior**
Discus comment section shows in any website that uses it when I'm using "Strict" mode in `about:preferences#privacy`.

**Desktop (please complete the following information):**
 - OS: Windows 10 Version 22H2 (OS Build 19045.4412)
 - Browser: Firefox
 - Version: 126.0 (64-bit)

**Comment by yokoffing** [comment]
I'm able to reproduce, but I'm unsure why Firefox discriminates between Disqus and the others.

**Comment by yokoffing** [comment]
It could be a bug in Firefox. From looking at the console, it seems Firefox still marks Disqus as Tracking even after adding an exception.

`socialtracking.skipURLs` isn't needed because Firefox ETP only categorizes Disqus as Tracking and not Social Media Tracking.

So for now, you'd have to use Standard or Custom ETP where **Tracking content** is  set to **Only in private windows**.

**Comment by DoTrONoL** [comment]
Ok. So we need to wait for a 'fix' from Firefox, then.  _Should I (or you) report to them?_

Does It have a line code for user.js, or should I disable the ETP config in the user.js and set it manually in my Firefox? If that exist and, I appreciate it if you could give me this line code for the Custom ETP, getting the same benefits as Strict but with only this option "Only in private windows" changed.

---
_Idk if it could be considered as 'completed' as we're the ones waiting for a fix from Firefox, so I'll let it up to you **to close** the issue. Thx by your effort._

**Comment by yokoffing** [comment]
> Should I (or you) report to them?

Yes, open a bug report. https://bugzilla.mozilla.org/enter_bug.cgi

> Does It have a line code for user.js, or should I disable the ETP config in the user.js and set it manually in my Firefox?

You add `user_pref("browser.contentblocking.category", "custom");` at the bottom of your user.js, where it says **My Overrides**.

>  getting the same benefits as Strict but with only this option "Only in private windows" changed.

You need to:
1) Go to [Securefox](https://github.com/yokoffing/Betterfox/blob/main/Securefox.js)
2) Press **CTRL** + **F**
3) Search for **enabled with "Strict"**
4) Manually change these lines in `about:config` or add them to the bottom of your user.js, except for `privacy.trackingprotection.enabled`.

**Comment by DoTrONoL** [comment]
Thx. To be exactly, I had to use this line in **My Overrides** to make it to work properly `user_pref("privacy.trackingprotection.enabled", false);` as it wasn't coming disabled by default in `"custom"`

I read the Bugzilla forum and right now we have 6 reports if you search for "disqus comment" [in this link](https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox&component=Untriaged). The most active report is [this one](https://bugzilla.mozilla.org/show_bug.cgi?id=1875061). So I decided not to open a new issue, rather I'm informing [our context](https://bugzilla.mozilla.org/show_bug.cgi?id=1875061#c12) (this issue) to that bug report.

**Comment by yokoffing** [comment]
> I had to use this line in **My Overrides** to make it to work properly `user_pref("privacy.trackingprotection.enabled", false);`

Ahh, yeah. That makes sense, because Firefox also has `privacy.trackingprotection.pbmode.enabled` as a pref.

I don't advocate for Custom, nor do I use it. But you're correct here.

> I decided not to open a new issue

Good job searching for any related issues first. Hopefully they resolve it soon.
