### ISSUE TITLE
Smoothfox values in quotation marks

### ISSUE THREAD

**Issue by Kutschel** [yokoffing/Betterfox#294]
In your Smoothfox /  _NATURAL SMOOTH SCROLLING V3_ part of your js you use the following three values without quotation marks:
```
user_pref("general.smoothScroll.msdPhysics.slowdownMinDeltaRatio", 2);
user_pref("general.smoothScroll.currentVelocityWeighting", 1);
user_pref("general.smoothScroll.stopDecelerationWeighting", 1);
```

The three need to be in quotation ("") to be recognized by Firefox - like in the original config by AveYo: https://github.com/AveYo/fox/blob/main/Natural%20Smooth%20Scrolling%20for%20user.js

So this works:
```
user_pref("general.smoothScroll.msdPhysics.slowdownMinDeltaRatio", "2");
user_pref("general.smoothScroll.currentVelocityWeighting", "1");
user_pref("general.smoothScroll.stopDecelerationWeighting", "1");
```

This issue might be specific to my German formats. Without quotation I only get the default or previous correct values. Tested on both of my Windows devices.

**Comment by yokoffing** [comment]
Hmm. I wonder why I didn't include the quotation marks from those values. I don't recall any discussion about those.

Anyway, thanks for catching that!
