### ISSUE TITLE
copying an edited link with the http/s trimmed will not copy the full address 

### ISSUE THREAD

**Issue by zbikk** [yokoffing/Betterfox#308]
basically if you edit the link the in the search bar and paste it, it will not contain the http/s thing. here's a video demonstrating my point (sorry for phone video spectacle video recording doesn't fkn work):

https://github.com/user-attachments/assets/56029025-3249-4038-8cd2-fe84a4e55c71

**Comment by yokoffing** [comment]
I don't think this would be average user behavior. However, repeat the same steps after going into `about:config` and activating `browser.urlbar.untrimOnUserInteraction.featureGate`.

**Comment by zbikk** [comment]
copies the link successfully now, but when clicking on the search bar twice it will untrim the https

**Comment by yokoffing** [comment]
OK. Thanks for testing it out!

If ends up disrupting your workflow, add this pref to your overrides section:

```javascript
user_pref("browser.urlbar.trimHttps", false);
```

**Comment by zbikk** [comment]
thank you! this actually seems to be a bug on firefox's side https://bugzilla.mozilla.org/show_bug.cgi?id=1848715 which should hopefully be resolved soon, thanks for your work as always.

**Comment by yokoffing** [comment]
Thanks for sharing. I wondered if this was intended by the developers. It seems they'll fix everything in Nightly before releasing it to Stable: https://bugzilla.mozilla.org/show_bug.cgi?id=1848715#c15
