### ISSUE TITLE
Tab Previews

### ISSUE THREAD

**Issue by AuRiMaS666** [yokoffing/Betterfox#309]
https://github.com/yokoffing/Betterfox/blob/c0d65d409dcfa09a7d1ab31da30a71a109c5deed/Peskyfox.js#L508

Apparently, they have changed the naming for tab preview options with version 128 from:

```
browser.tabs.cardPreview.enabled

browser.tabs.cardPreview.showThumbnails
```

to:

```
browser.tabs.hoverPreview.enabled

browser.tabs.hoverPreview.showThumbnails
```

**Comment by yokoffing** [comment]
Thank you!
