### ISSUE TITLE
Bring back old Clear All History dialog

### ISSUE THREAD

**Issue by gunir** [yokoffing/Betterfox#312]
Latest Firefox is using this nerfed dialog:
![image](https://github.com/user-attachments/assets/d0ea01b6-bb59-44d2-882f-f48aee7d8006)

Set `privacy.sanitize.useOldClearHistoryDialog` to `true`.

![image](https://github.com/user-attachments/assets/b549c0c9-907a-4e30-8f9b-68c909d2b127)

**Comment by yokoffing** [comment]
Yes, and unless they backtrack on it, the legacy settings may not be around for long.

I still have both listed in Securefox and only the old prefs on the Optional Hardening page. But I'll be curious when they remove the old prefs, or make the new v2 prefs the default, etc. We'll see.
