### ISSUE TITLE
[Suggestion] Probably recognize Zen Browser in Browser Integration part of README

### ISSUE THREAD

**Issue by win98se** [yokoffing/Betterfox#314]
[Zen Browser](https://github.com/zen-browser/desktop) has integrated [a modified version of Betterfox](https://github.com/zen-browser/desktop/issues/292#issuecomment-2294589485). Betterfox is also mentioned in [the repo's README](https://github.com/zen-browser/desktop/commit/5f9f555083ac53de8e1743018e73f0e86f2ae6e8), and [the respective part(s)](https://github.com/zen-browser/desktop/blob/main/src/browser/app/profile/better-fox.js).

**Comment by yokoffing** [comment]
> Betterfox is also mentioned in the repo's README

Yeah, only after I [suggested](https://www.reddit.com/r/browsers/comments/1eqg9ad/comment/lhzcnst/) it :laughing:

> recognize Zen Browser in Browser Integration

Already planned for next release https://github.com/yokoffing/Betterfox/commit/1ab6dcdf076c4197979746c645847ce141c13509
