### ISSUE TITLE
Fix release

### ISSUE THREAD

**Issue by Icey-Glitch** [yokoffing/Betterfox#316]
Current release has syntax issues

**Comment by yokoffing** [comment]
This takes the cake for being the most unhelpful issue report I’ve received.

**Comment by Icey-Glitch** [comment]
sorry, i will provide the file and line. i didn't realize i was being rude. i apologize

**Comment by Icey-Glitch** [comment]
your resolved it in this comment it would be nice to update the release though as it is somewhat breaking https://github.com/yokoffing/Betterfox/commit/c0d65d409dcfa09a7d1ab31da30a71a109c5deed

**Comment by yokoffing** [comment]
It is fixed on both the main branch and esr128 branch? https://github.com/yokoffing/Betterfox/blob/29f081696200afc3af6a43f300a8000af18fa86e/Securefox.js#L649

**Comment by Icey-Glitch** [comment]
I miss understood the release model I will mark this as completed. sorry for wasting your time with this
