### ISSUE TITLE
How to get rid of Google signin snippet on various websites ?

### ISSUE THREAD

**Issue by wealstarr** [yokoffing/Betterfox#319]
## REPORT
When I visit many sites such as Reddit, Superuser etc on the top right corner, a Google snippet appears asking to sign in. 

**To Reproduce**
log out of Reddit, Superuser etc and reload the page.

**Expected behavior**
The Google signin widget shouldn't appear

**Screenshots**
![Capture](https://github.com/user-attachments/assets/cf8f6a0a-70c1-4618-81b7-9b171d188891)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Zen Browser a.35
 - Version: 129 (Betterfox version)

**Additional context**
I tried adding the `user_pref("dom.webnotifications.serviceworker.enabled", false);` but this flag doesn't seem to have any impact. I can still see it.

Any help will be greatly appreciated.

Kind regards

**Comment by yokoffing** [comment]
This is an issue for adblockers, not browsers.

1. https://ublockorigin.com/
2. https://github.com/yokoffing/filterlists/blob/2a83d5a3380ab4eaa62b988f5fd46715c8eefa40/annoyance_list.txt#L963
3. https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters

**Comment by wealstarr** [comment]
@yokoffing Thank you for the response. Didn't know you also had your own filterlists. What else that you do that we, casual users aren't aware of ? 

Btw, many thanks for all this work you do, we've been greatly benefited from your skills and hardwork.

Meaning to ask you one more thing, don't wanna create a separate issue, in Firefox, how do you disable the option for addons auto updating through user.js ?

Kind regards

**Comment by philg-dev** [comment]
@wealstarr 

Regarding the auto-update of addons, I think these are the relevant properties in `about:config`

```
extensions.update.autoUpdateDefault
extensions.update.enabled
```

I didn't verify that, but I would guess that `extensions.update.enabled` globally controls if any extensions get updated at all. (Maybe "system extensions" and/or dictionaries are not influenced by that flag.)

The `extensions.update.autoUpdateDefault` flag seems like a great option if you would like to avoid updates by default, but still be able to opt-in to updates for specific addons.

Please verify yourself if these settings actually work this way - I just found them in `about:config`.

**Comment by yokoffing** [comment]
> What else that you do that we, casual users aren't aware of ?

https://github.com/yokoffing/Betterfox?tab=readme-ov-file#required-reading

**Comment by wealstarr** [comment]
@philg-dev 

Yes, this was it `extensions.update.autoUpdateDefault`

Many thanks for the help. It's complete now.
