### ISSUE TITLE
Use native title bar buttons in Linux with a custom theme

### ISSUE THREAD

**Issue by M0-7** [yokoffing/Betterfox#320]
Usually when you switch the theme in firefox (Linux) the window decorations in the title bar change to something which is non-native but if you set:

"widget.gtk.non-native-titlebar-buttons.enabled" to false

Then the issue goes away. Would you consider adding this? This works great on gnome. Haven't tested it yet on kde

### Before
![image](https://github.com/user-attachments/assets/6942e3cc-d4c6-44c3-a3e4-33a8ff1a44b6)

### After
![image](https://github.com/user-attachments/assets/2eeca80b-e974-4cd6-9c34-5094ba375205)

**Comment by yokoffing** [comment]
Idk if I want to make this a default, because of how fractured Linux is, and how many Linux users customize their setup. But I have added as an option in Peskyfox. https://github.com/yokoffing/Betterfox/commit/2149f50d818ac7846adef4d67b248983f5b8db54
