### ISSUE TITLE
Not able to play DRM content on https://www.southparkstudios.com/

### ISSUE THREAD

**Issue by anthonyabbasi** [yokoffing/Betterfox#322]
## BEFORE YOU BEGIN
I have attempted the following troubleshooting suggestions:
- [x] The issue persists when using Firefox in [Troubleshoot Mode](https://support.mozilla.org/en-US/kb/diagnose-firefox-issues-using-troubleshoot-mode).
- [x] Disabled DNS-level content blocking (AdGuard Home, NextDNS, Control D, RethinkDNS, PiHole, etc), [cleared my DNS cache](https://www.pcmag.com/how-to/how-to-flush-your-dns-cache), and used my ISP's DNS resolver (if applicable).
- [x] [Cleared website data](https://support.mozilla.org/en-US/kb/clear-cookies-and-site-data-firefox), restarted Firefox, and my issue persists.
- [x] I have created a [new profile](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles). The issue persists when using the current [user.js](https://github.com/yokoffing/Betterfox/blob/master/user.js) file on GitHub. (Must be in a new profile and a new user.js!)

## REPORT
**Describe the bug**
DRM content on the website https://www.southparkstudios.com/ won't play on my firefox profile with betterfox installed on, drm content enabled in settings and also the google widevine plugin enabled in plugins.

**To Reproduce**
```
1. Go to 'https://www.southparkstudios.com/'
2. Scroll down and click any episode
3. See error
```

**Expected behavior**
Normally, the video would just play

**Screenshots**
![image](https://github.com/user-attachments/assets/e31f8cb4-e4ec-467d-8046-ae123832c156)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 23H2
 - Browser: Firefox
 - Version: 130.0 (64-bit)

**Additional context**
I tried changing the google widevine plugin from 'default' to 'enabled' and 'disabled' but that didn't fix anything
I am currently using the base user.js file with the following added overrides:
```javscript
/****************************************************************************
 * START: MY OVERRIDES                                                      *
****************************************************************************/
// visit https://github.com/yokoffing/Betterfox/wiki/Common-Overrides
// visit https://github.com/yokoffing/Betterfox/wiki/Optional-Hardening
// Enter your personal overrides below this line:

// PREF: allow websites to ask you for your location
user_pref("permissions.default.geo", 0);

// PREF: allow websites to ask you to receive site notifications
user_pref("permissions.default.desktop-notification", 0);

// PREF: restore search engine suggestions
user_pref("browser.search.suggest.enabled", true);

// PREF: enable container tabs
user_pref("privacy.userContext.enabled", true);

// PREF: enable GPU-accelerated Canvas2D [WINDOWS]
user_pref("gfx.canvas.accelerated", true);

// PREF: disable Firefox Sync
user_pref("identity.fxaccounts.enabled", false);

// PREF: disable the Firefox View tour from popping up
user_pref("browser.firefox-view.feature-tour", "{\"screen\":\"\",\"complete\":true}");

// PREF: disable login manager
user_pref("signon.rememberSignons", false);

// PREF: disable address and credit card manager
user_pref("extensions.formautofill.addresses.enabled", false);
user_pref("extensions.formautofill.creditCards.enabled", false);

// PREF: ask where to save every file
user_pref("browser.download.useDownloadDir", false);

/****************************************************************************
 * SECTION: SMOOTHFOX                                                       *
****************************************************************************/
// visit https://github.com/yokoffing/Betterfox/blob/main/Smoothfox.js
// Enter your scrolling overrides below this line:

// credit: https://github.com/AveYo/fox/blob/cf56d1194f4e5958169f9cf335cd175daa48d349/Natural%20Smooth%20Scrolling%20for%20user.js
// recommended for 120hz+ displays
// largely matches Chrome flags: Windows Scrolling Personality and Smooth Scrolling
user_pref("apz.overscroll.enabled", true); // DEFAULT NON-LINUX
user_pref("general.smoothScroll", true); // DEFAULT
user_pref("general.smoothScroll.msdPhysics.continuousMotionMaxDeltaMS", 12);
user_pref("general.smoothScroll.msdPhysics.enabled", true);
user_pref("general.smoothScroll.msdPhysics.motionBeginSpringConstant", 600);
user_pref("general.smoothScroll.msdPhysics.regularSpringConstant", 650);
user_pref("general.smoothScroll.msdPhysics.slowdownMinDeltaMS", 25);
user_pref("general.smoothScroll.msdPhysics.slowdownMinDeltaRatio", "2");
user_pref("general.smoothScroll.msdPhysics.slowdownSpringConstant", 250);
user_pref("general.smoothScroll.currentVelocityWeighting", "1");
user_pref("general.smoothScroll.stopDecelerationWeighting", "1");
user_pref("mousewheel.default.delta_multiplier_y", 300); // 250-400; adjust this number to your liking
```

**Comment by yokoffing** [comment]
I am able to reproduce. However, if I disable uBO, it works. Did you rule out that this was an adblock issue?

**Comment by yokoffing** [comment]
The video plays for me if I allow `cdn.privacy.paramount.com` https://github.com/yokoffing/filterlists/commit/5af3fc09c303eab90220343de1dcbed79c83f2b7

**Comment by yokoffing** [comment]
>  I just disabled the enhanced tracker protection built into firefox and realised that was the actual issue

I didn't disable ETP to get it to work. In fact, my Firefox is blocking more than those requests:

![etp southpark](https://github.com/user-attachments/assets/06e603d7-f11e-420c-bde8-a02a6c0cfe64)

`fwmrm.net` doesn't appear at all.

Can you disable `gfx.canvas.accelerated` to see if that changes anything?

>  I've tried on a new profile with uBO only installed and the video works perfectly.

What about a new profile + user.js (not overrides) + uBO?

**Comment by anthonyabbasi** [comment]
> Can you disable `gfx.canvas.accelerated` to see if that changes anything?

I have tried this but the issue still persists. 
> What about a new profile + user.js (not overrides) + uBO?

Yeah I've tried this and it works fine, I reported the issue as broken on the Enhanced Tracker Protection popout.

**Comment by yokoffing** [comment]
Ok. Sometimes different requests are served based on one's location.
