### ISSUE TITLE
[Help] How do I block this nuisance?

### ISSUE THREAD

**Issue by wxmup** [yokoffing/Betterfox#329]
Since firefox was updated to 131,this thing circled by this circle on the picture has appeared like moss and there is no way to remove it from the toolbar! How do I disable 'List All Tabs' so that it doesn't show an icon in the toolbar?What should I do?
![截图 2024-10-05 13-33-53](https://github.com/user-attachments/assets/4117dcfc-e693-4774-8603-7efbb62b25ec)

![图片](https://github.com/user-attachments/assets/56cec496-c38d-4192-9e07-3d9533c77770)

**Comment by yokoffing** [comment]
See https://www.reddit.com/r/firefox/comments/1fvhnfy/how_to_remove_the_list_all_tabs_button_from/

**Comment by wxmup** [comment]
> See https://www.reddit.com/r/firefox/comments/1fvhnfy/how_to_remove_the_list_all_tabs_button_from/

Thank you sir! It successly solve this problem!
