### ISSUE TITLE
Importing one user.js into another?

### ISSUE THREAD

**Issue by matru** [yokoffing/Betterfox#332]
I would like to separate betterfox's user.js and my custom changes in it, so instead of manually copy pasting my custom changes to the updated betterfox user.js every time it updates, would be great to have one that is being git pulled all the time, and another that imports it and applies the custom changes. Would this work with how Firefox handles things, I have no idea what js version/handling they use for such thing.

File 1 (betterfox_user.js):

```
/** DISK CACHE ***/
user_pref("browser.cache.jsbc_compression_level", 3);

/** MEDIA CACHE ***/
user_pref("media.memory_cache_max_size", 65536);
user_pref("media.cache_readahead_limit", 7200);
user_pref("media.cache_resume_threshold", 3600);
```

File 2 (user.js):

```
/** Import Betterfox and make custom changes ***/

import './betterfox_user.js';

user_pref("media.cache_readahead_limit", 3600);
user_pref("browser.urlbar.trimHttps", false);
```

This way I always keep user.js clean, can git pull/curl when updates are needed, and play with my custom config without touching the betterfox config?

**Comment by Denperidge** [comment]
By coincidence I implemented a similar feature to this in the installer, if that workflow is okay for you!

**Comment by yokoffing** [comment]
Please see https://github.com/yokoffing/Betterfox/pull/318
