### ISSUE TITLE
List of superfluous entries as of Firefox 132

### ISSUE THREAD

**Issue by NewKidOnTheBlock** [yokoffing/Betterfox#336]
I've combed through the BetterFox user.js and found a lot of tweaks that were not needed anymore, since they have become the Firefox Default. Check these out:

```
user_pref("network.cookie.sameSite.noneRequiresSecure", true);
user_pref("browser.urlbar.quicksuggest.enabled", false);
user_pref("browser.urlbar.suggest.quicksuggest.sponsored", false);
user_pref("browser.urlbar.suggest.quicksuggest.nonsponsored", false);
user_pref("browser.crashReports.unsubmittedCheck.autoSubmit2", false);
user_pref("browser.newtabpage.activity-stream.newtabWallpapers.v2.enabled", true);

```
These two settings don't exist anymore:
```
user_pref("webchannel.allowObject.urlWhitelist", "");
user_pref("browser.tabs.tabmanager.enabled", false);
```

And here is a third group surrounding _prefetching_ that gets automagically taken care of after you have installed µBlock Origin:
```
network.dns.disablePrefetch 
network.predictor.enabled
network.predictor.enable-prefetch
network.prefetch-next
```

**Comment by yokoffing** [comment]
`browser.urlbar.quicksuggest.enabled` is still enabled for me in 132.0 (USA). Same for both the `sponsored` prefs.

---


```
network.dns.disablePrefetch 
network.predictor.enabled
network.predictor.enable-prefetch
network.prefetch-next
```

These network prefetching prefs help privacy in default Firefox without uBO installed. (Not everyone uses uBO, for whatever reason.)

Off-topic but worth mentioning: With uBO installed, disabling its `disable prefetch` setting and enabling these prefs doesn't speed things up. I tested this myself many times.

**Comment by NewKidOnTheBlock** [comment]
`user_pref("network.predictor.enabled", false);` = Default in Firefox 132 and Thunderbird 128

**Comment by yokoffing** [comment]
> `user_pref("network.predictor.enable-prefetch", false);`

It's enabled by default in Nightly, but is there as a "just in case" for when they flip it on. I may remove it, but it isn't hurting anything.

> `gfx.canvas.accelerated`

Enabled by default on macOS and Linux. Starting with Firefox v.133, it will also be [enabled by default on Windows](https://www.mozilla.org/en-US/firefox/133.0beta/releasenotes/). 

This pref is mentioned on the [Common Overrides](https://github.com/yokoffing/Betterfox/wiki/Common-Overrides#gpu-accelerated-canvas2d) page. I suggest(ed) users to enable it if their system has a dGPU. I believe Mozilla has resolved any issues related to Windows integrated GPUs.
