### ISSUE TITLE
Site drogariaspacheco.com.br doesn't work with betterfox

### ISSUE THREAD

**Issue by ramonomar** [yokoffing/Betterfox#341]
I have attempted the following troubleshooting suggestions:
- [x] The issue persists when using Firefox in [Troubleshoot Mode](https://support.mozilla.org/en-US/kb/diagnose-firefox-issues-using-troubleshoot-mode).
- [x] Disabled DNS-level content blocking (AdGuard Home, NextDNS, Control D, RethinkDNS, PiHole, etc.), [cleared my DNS cache](https://www.pcmag.com/how-to/how-to-flush-your-dns-cache), and used my ISP's DNS resolver (if applicable).
- [x] [Cleared website data](https://support.mozilla.org/en-US/kb/clear-cookies-and-site-data-firefox), restarted Firefox, and my issue persists.
- [x] I have created a [new profile](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles). The issue persists when using the current [user.js](https://github.com/yokoffing/Betterfox/blob/master/user.js) file on GitHub. (Must be in a new profile and a new user.js!)

## REPORT

**Describe the bug**
When accessing the website [www.drogariaspacheco.com.br](https://www.drogariaspacheco.com.br), certain functionalities are not working. The search bar is unresponsive, and clicking on the "Bem vindo, Faça seu login ou Cadastro" ("Welcome, Login or Register") button does not produce any action.

**To Reproduce**
1. Go to https://www.drogariaspacheco.com.br
2. Attempt to use the search bar at the top of the page (try to search for any product)
3. Click on the "Bem vindo, Faça seu login ou Cadastro" button
4. Notice that both the search bar and the login/register button are not functioning

**Expected behavior**
- The search bar should allow users to input text and search for products.
- Clicking on the "Bem vindo, Faça seu login ou Cadastro" button should prompt the login or registration process.

**Screenshots**
*If applicable, please find attached screenshots illustrating the issue.*

**Desktop (please complete the following information):**
- OS: Windows 10 x64
- Browser: Firefox
- Version: 133.0

**Additional context**
I have ensured that no other extensions are causing the issue by following all the recommended troubleshooting steps. The problem only occurs when the Betterfox is active.

**Comment by yokoffing** [comment]
The site does not work for me on a new profile with Firefox 132.0.2 (USA).

**Comment by ramonomar** [comment]
> The site does not work for me on a new profile with Firefox 132.0.2 (USA).

For me, it does work on a new profile

https://github.com/user-attachments/assets/4c4b5991-196c-40e6-b3a2-d7763a44340d

**Comment by ramonomar** [comment]
> I tried again today, except on macOS. Downgrading to **Standard** tracking protection from **Strict** fixed it for me.
> 
> Add line to your overrides:
> 
> ```
> user_pref("browser.contentblocking.category", "standard"); 
> ```

Thank you, it worked.
