### ISSUE TITLE
User.js and Password manager

### ISSUE THREAD

**Issue by imanubdesigner** [yokoffing/Betterfox#354]
First of all, congratulations for this awesome work.

It's not a problem, but I would just like to know how to restore the old password manager that recommends you to save the password in a new site, so you don't have to enter it every time. 

Since I put the user.js the window no longer appears and I am forced to click on the key symbol. I would like this thing to return as default firefox.

![firefox_KKgDWhLsvG](https://github.com/user-attachments/assets/0387a9bb-21fc-465f-bee8-b7b2aabb7d4c)

I mean the windows in my screenshot above

What do I need to change in User.js?

**Comment by yokoffing** [comment]
1. https://github.com/yokoffing/Betterfox?tab=readme-ov-file#required-reading
2. https://github.com/yokoffing/Betterfox/wiki/Common-Overrides#instructions
3. https://github.com/yokoffing/Betterfox/wiki/Common-Overrides#password-credit-card-and-address-management

**Comment by imanubdesigner** [comment]
In the override section, just enter these?

// PREF: restore login manager
user_pref("signon.rememberSignons", true);

// PREF: restore address and credit card manager
user_pref("extensions.formautofill.addresses.enabled", true);
user_pref("extensions.formautofill.creditCards.enabled", true);

**Comment by imanubdesigner** [comment]
No, It still doesn't work, even though I added these lines.

**Comment by imanubdesigner** [comment]
> Thank you. Then it most likely relates to one of these:
> 
> https://github.com/yokoffing/Betterfox/blob/09dd87a3abcb15a88798941e5ed74e4aa593108c/user.js#L104-L107
> 
> It sounds like what you're looking for is `user_pref("signon.formlessCapture.enabled", true);`. Add that to your overrides section and restart.
> 
> If you want this same popup in Private Browsing (not recommended), then you can also add ` user_pref("signon.privateBrowsingCapture.enabled", true);`.
> 
> Most of the userbase doesn't use the native password manager, so it's good to get feedback on this issue.

Thank you so much! Yep... You're right! `user_pref("signon.formlessCapture.enabled", true);` in my Overrides solved the problem! 

![notepad++_KSPn1ErtHH](https://github.com/user-attachments/assets/b02b0dce-5692-4d55-ace4-4f17ecd81c82)

**Comment by yokoffing** [comment]
I added this to the overrides doc as well.

**Comment by imanubdesigner** [comment]
Thank you so much, Yokoffing. <3 Mostly for patience. I love things done well (I'm very picky)
